/*
CrispHive Developer API

Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the Date type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Date{}

// Date struct for Date
type Date struct {
	TimeTime *string `json:"time.Time,omitempty"`
}

// NewDate instantiates a new Date object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDate() *Date {
	this := Date{}
	return &this
}

// NewDateWithDefaults instantiates a new Date object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDateWithDefaults() *Date {
	this := Date{}
	return &this
}

// GetTimeTime returns the TimeTime field value if set, zero value otherwise.
func (o *Date) GetTimeTime() string {
	if o == nil || IsNil(o.TimeTime) {
		var ret string
		return ret
	}
	return *o.TimeTime
}

// GetTimeTimeOk returns a tuple with the TimeTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Date) GetTimeTimeOk() (*string, bool) {
	if o == nil || IsNil(o.TimeTime) {
		return nil, false
	}
	return o.TimeTime, true
}

// HasTimeTime returns a boolean if a field has been set.
func (o *Date) HasTimeTime() bool {
	if o != nil && !IsNil(o.TimeTime) {
		return true
	}

	return false
}

// SetTimeTime gets a reference to the given string and assigns it to the TimeTime field.
func (o *Date) SetTimeTime(v string) {
	o.TimeTime = &v
}

func (o Date) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Date) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimeTime) {
		toSerialize["time.Time"] = o.TimeTime
	}
	return toSerialize, nil
}

type NullableDate struct {
	value *Date
	isSet bool
}

func (v NullableDate) Get() *Date {
	return v.value
}

func (v *NullableDate) Set(val *Date) {
	v.value = val
	v.isSet = true
}

func (v NullableDate) IsSet() bool {
	return v.isSet
}

func (v *NullableDate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDate(val *Date) *NullableDate {
	return &NullableDate{value: val, isSet: true}
}

func (v NullableDate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


