/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobRequestEmergencyPreviewRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestEmergencyPreviewRequest{}

// JobRequestEmergencyPreviewRequest struct for JobRequestEmergencyPreviewRequest
type JobRequestEmergencyPreviewRequest struct {
	// Fate of displaced jobs: reschedule (default — pushed to later windows) or reassign (handed to another feasible technician at their ORIGINAL time; no-capacity jobs fall back to reschedule).
	DisplacementMode *string `json:"displacement_mode,omitempty"`
	// ID of the P0 job to insert.
	EmergencyJobId string `json:"emergency_job_id"`
	// Cascade mode: overtime = displaced jobs stay same-day (tech works late); next_day = overflow rolls to the next working day.
	Mode string `json:"mode"`
	// Desired start — business-local naive datetime, no offset. Must be in the future.
	StartAt string `json:"start_at"`
	// Target technician (must belong to the business).
	TechnicianId string `json:"technician_id"`
}

type _JobRequestEmergencyPreviewRequest JobRequestEmergencyPreviewRequest

// NewJobRequestEmergencyPreviewRequest instantiates a new JobRequestEmergencyPreviewRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestEmergencyPreviewRequest(emergencyJobId string, mode string, startAt string, technicianId string) *JobRequestEmergencyPreviewRequest {
	this := JobRequestEmergencyPreviewRequest{}
	this.EmergencyJobId = emergencyJobId
	this.Mode = mode
	this.StartAt = startAt
	this.TechnicianId = technicianId
	return &this
}

// NewJobRequestEmergencyPreviewRequestWithDefaults instantiates a new JobRequestEmergencyPreviewRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestEmergencyPreviewRequestWithDefaults() *JobRequestEmergencyPreviewRequest {
	this := JobRequestEmergencyPreviewRequest{}
	return &this
}

// GetDisplacementMode returns the DisplacementMode field value if set, zero value otherwise.
func (o *JobRequestEmergencyPreviewRequest) GetDisplacementMode() string {
	if o == nil || IsNil(o.DisplacementMode) {
		var ret string
		return ret
	}
	return *o.DisplacementMode
}

// GetDisplacementModeOk returns a tuple with the DisplacementMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyPreviewRequest) GetDisplacementModeOk() (*string, bool) {
	if o == nil || IsNil(o.DisplacementMode) {
		return nil, false
	}
	return o.DisplacementMode, true
}

// HasDisplacementMode returns a boolean if a field has been set.
func (o *JobRequestEmergencyPreviewRequest) HasDisplacementMode() bool {
	if o != nil && !IsNil(o.DisplacementMode) {
		return true
	}

	return false
}

// SetDisplacementMode gets a reference to the given string and assigns it to the DisplacementMode field.
func (o *JobRequestEmergencyPreviewRequest) SetDisplacementMode(v string) {
	o.DisplacementMode = &v
}

// GetEmergencyJobId returns the EmergencyJobId field value
func (o *JobRequestEmergencyPreviewRequest) GetEmergencyJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmergencyJobId
}

// GetEmergencyJobIdOk returns a tuple with the EmergencyJobId field value
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyPreviewRequest) GetEmergencyJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmergencyJobId, true
}

// SetEmergencyJobId sets field value
func (o *JobRequestEmergencyPreviewRequest) SetEmergencyJobId(v string) {
	o.EmergencyJobId = v
}

// GetMode returns the Mode field value
func (o *JobRequestEmergencyPreviewRequest) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyPreviewRequest) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *JobRequestEmergencyPreviewRequest) SetMode(v string) {
	o.Mode = v
}

// GetStartAt returns the StartAt field value
func (o *JobRequestEmergencyPreviewRequest) GetStartAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyPreviewRequest) GetStartAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartAt, true
}

// SetStartAt sets field value
func (o *JobRequestEmergencyPreviewRequest) SetStartAt(v string) {
	o.StartAt = v
}

// GetTechnicianId returns the TechnicianId field value
func (o *JobRequestEmergencyPreviewRequest) GetTechnicianId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TechnicianId
}

// GetTechnicianIdOk returns a tuple with the TechnicianId field value
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyPreviewRequest) GetTechnicianIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TechnicianId, true
}

// SetTechnicianId sets field value
func (o *JobRequestEmergencyPreviewRequest) SetTechnicianId(v string) {
	o.TechnicianId = v
}

func (o JobRequestEmergencyPreviewRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestEmergencyPreviewRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplacementMode) {
		toSerialize["displacement_mode"] = o.DisplacementMode
	}
	toSerialize["emergency_job_id"] = o.EmergencyJobId
	toSerialize["mode"] = o.Mode
	toSerialize["start_at"] = o.StartAt
	toSerialize["technician_id"] = o.TechnicianId
	return toSerialize, nil
}

func (o *JobRequestEmergencyPreviewRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"emergency_job_id",
		"mode",
		"start_at",
		"technician_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobRequestEmergencyPreviewRequest := _JobRequestEmergencyPreviewRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobRequestEmergencyPreviewRequest)

	if err != nil {
		return err
	}

	*o = JobRequestEmergencyPreviewRequest(varJobRequestEmergencyPreviewRequest)

	return err
}

type NullableJobRequestEmergencyPreviewRequest struct {
	value *JobRequestEmergencyPreviewRequest
	isSet bool
}

func (v NullableJobRequestEmergencyPreviewRequest) Get() *JobRequestEmergencyPreviewRequest {
	return v.value
}

func (v *NullableJobRequestEmergencyPreviewRequest) Set(val *JobRequestEmergencyPreviewRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestEmergencyPreviewRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestEmergencyPreviewRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestEmergencyPreviewRequest(val *JobRequestEmergencyPreviewRequest) *NullableJobRequestEmergencyPreviewRequest {
	return &NullableJobRequestEmergencyPreviewRequest{value: val, isSet: true}
}

func (v NullableJobRequestEmergencyPreviewRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestEmergencyPreviewRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


