/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the JobRequestEmergencyCandidate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestEmergencyCandidate{}

// JobRequestEmergencyCandidate struct for JobRequestEmergencyCandidate
type JobRequestEmergencyCandidate struct {
	// Minutes of work already booked on this technician that day (workload context).
	BookedMinutes *int32 `json:"booked_minutes,omitempty"`
	// The displaced jobs, grouped per business-local day (same shape as the preview endpoint) — what the coordinator reviews before committing.
	Days []JobRequestRescheduleDay `json:"days,omitempty"`
	// Estimated distance from the tech's start location to the site, in kilometers.
	DistanceKm *float32 `json:"distance_km,omitempty"`
	// Candidate technician's full name.
	FullName *string `json:"full_name,omitempty"`
	// Number of the job's desired skills this technician matches.
	MatchedSkills *int32 `json:"matched_skills,omitempty"`
	// UUID of the candidate technician.
	TechnicianId *string `json:"technician_id,omitempty"`
	// How many jobs choosing this tech would push (0 = free slot).
	TotalMoves *int32 `json:"total_moves,omitempty"`
	// Smart-assign engine ranking score (higher = better fit).
	TotalScore *float32 `json:"total_score,omitempty"`
	// ETA estimate in minutes from the tech's start location to the site — static origin (no live GPS), rank hint not a promise.
	TravelMinutes *float32 `json:"travel_minutes,omitempty"`
}

// NewJobRequestEmergencyCandidate instantiates a new JobRequestEmergencyCandidate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestEmergencyCandidate() *JobRequestEmergencyCandidate {
	this := JobRequestEmergencyCandidate{}
	return &this
}

// NewJobRequestEmergencyCandidateWithDefaults instantiates a new JobRequestEmergencyCandidate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestEmergencyCandidateWithDefaults() *JobRequestEmergencyCandidate {
	this := JobRequestEmergencyCandidate{}
	return &this
}

// GetBookedMinutes returns the BookedMinutes field value if set, zero value otherwise.
func (o *JobRequestEmergencyCandidate) GetBookedMinutes() int32 {
	if o == nil || IsNil(o.BookedMinutes) {
		var ret int32
		return ret
	}
	return *o.BookedMinutes
}

// GetBookedMinutesOk returns a tuple with the BookedMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyCandidate) GetBookedMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.BookedMinutes) {
		return nil, false
	}
	return o.BookedMinutes, true
}

// HasBookedMinutes returns a boolean if a field has been set.
func (o *JobRequestEmergencyCandidate) HasBookedMinutes() bool {
	if o != nil && !IsNil(o.BookedMinutes) {
		return true
	}

	return false
}

// SetBookedMinutes gets a reference to the given int32 and assigns it to the BookedMinutes field.
func (o *JobRequestEmergencyCandidate) SetBookedMinutes(v int32) {
	o.BookedMinutes = &v
}

// GetDays returns the Days field value if set, zero value otherwise.
func (o *JobRequestEmergencyCandidate) GetDays() []JobRequestRescheduleDay {
	if o == nil || IsNil(o.Days) {
		var ret []JobRequestRescheduleDay
		return ret
	}
	return o.Days
}

// GetDaysOk returns a tuple with the Days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyCandidate) GetDaysOk() ([]JobRequestRescheduleDay, bool) {
	if o == nil || IsNil(o.Days) {
		return nil, false
	}
	return o.Days, true
}

// HasDays returns a boolean if a field has been set.
func (o *JobRequestEmergencyCandidate) HasDays() bool {
	if o != nil && !IsNil(o.Days) {
		return true
	}

	return false
}

// SetDays gets a reference to the given []JobRequestRescheduleDay and assigns it to the Days field.
func (o *JobRequestEmergencyCandidate) SetDays(v []JobRequestRescheduleDay) {
	o.Days = v
}

// GetDistanceKm returns the DistanceKm field value if set, zero value otherwise.
func (o *JobRequestEmergencyCandidate) GetDistanceKm() float32 {
	if o == nil || IsNil(o.DistanceKm) {
		var ret float32
		return ret
	}
	return *o.DistanceKm
}

// GetDistanceKmOk returns a tuple with the DistanceKm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyCandidate) GetDistanceKmOk() (*float32, bool) {
	if o == nil || IsNil(o.DistanceKm) {
		return nil, false
	}
	return o.DistanceKm, true
}

// HasDistanceKm returns a boolean if a field has been set.
func (o *JobRequestEmergencyCandidate) HasDistanceKm() bool {
	if o != nil && !IsNil(o.DistanceKm) {
		return true
	}

	return false
}

// SetDistanceKm gets a reference to the given float32 and assigns it to the DistanceKm field.
func (o *JobRequestEmergencyCandidate) SetDistanceKm(v float32) {
	o.DistanceKm = &v
}

// GetFullName returns the FullName field value if set, zero value otherwise.
func (o *JobRequestEmergencyCandidate) GetFullName() string {
	if o == nil || IsNil(o.FullName) {
		var ret string
		return ret
	}
	return *o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyCandidate) GetFullNameOk() (*string, bool) {
	if o == nil || IsNil(o.FullName) {
		return nil, false
	}
	return o.FullName, true
}

// HasFullName returns a boolean if a field has been set.
func (o *JobRequestEmergencyCandidate) HasFullName() bool {
	if o != nil && !IsNil(o.FullName) {
		return true
	}

	return false
}

// SetFullName gets a reference to the given string and assigns it to the FullName field.
func (o *JobRequestEmergencyCandidate) SetFullName(v string) {
	o.FullName = &v
}

// GetMatchedSkills returns the MatchedSkills field value if set, zero value otherwise.
func (o *JobRequestEmergencyCandidate) GetMatchedSkills() int32 {
	if o == nil || IsNil(o.MatchedSkills) {
		var ret int32
		return ret
	}
	return *o.MatchedSkills
}

// GetMatchedSkillsOk returns a tuple with the MatchedSkills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyCandidate) GetMatchedSkillsOk() (*int32, bool) {
	if o == nil || IsNil(o.MatchedSkills) {
		return nil, false
	}
	return o.MatchedSkills, true
}

// HasMatchedSkills returns a boolean if a field has been set.
func (o *JobRequestEmergencyCandidate) HasMatchedSkills() bool {
	if o != nil && !IsNil(o.MatchedSkills) {
		return true
	}

	return false
}

// SetMatchedSkills gets a reference to the given int32 and assigns it to the MatchedSkills field.
func (o *JobRequestEmergencyCandidate) SetMatchedSkills(v int32) {
	o.MatchedSkills = &v
}

// GetTechnicianId returns the TechnicianId field value if set, zero value otherwise.
func (o *JobRequestEmergencyCandidate) GetTechnicianId() string {
	if o == nil || IsNil(o.TechnicianId) {
		var ret string
		return ret
	}
	return *o.TechnicianId
}

// GetTechnicianIdOk returns a tuple with the TechnicianId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyCandidate) GetTechnicianIdOk() (*string, bool) {
	if o == nil || IsNil(o.TechnicianId) {
		return nil, false
	}
	return o.TechnicianId, true
}

// HasTechnicianId returns a boolean if a field has been set.
func (o *JobRequestEmergencyCandidate) HasTechnicianId() bool {
	if o != nil && !IsNil(o.TechnicianId) {
		return true
	}

	return false
}

// SetTechnicianId gets a reference to the given string and assigns it to the TechnicianId field.
func (o *JobRequestEmergencyCandidate) SetTechnicianId(v string) {
	o.TechnicianId = &v
}

// GetTotalMoves returns the TotalMoves field value if set, zero value otherwise.
func (o *JobRequestEmergencyCandidate) GetTotalMoves() int32 {
	if o == nil || IsNil(o.TotalMoves) {
		var ret int32
		return ret
	}
	return *o.TotalMoves
}

// GetTotalMovesOk returns a tuple with the TotalMoves field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyCandidate) GetTotalMovesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalMoves) {
		return nil, false
	}
	return o.TotalMoves, true
}

// HasTotalMoves returns a boolean if a field has been set.
func (o *JobRequestEmergencyCandidate) HasTotalMoves() bool {
	if o != nil && !IsNil(o.TotalMoves) {
		return true
	}

	return false
}

// SetTotalMoves gets a reference to the given int32 and assigns it to the TotalMoves field.
func (o *JobRequestEmergencyCandidate) SetTotalMoves(v int32) {
	o.TotalMoves = &v
}

// GetTotalScore returns the TotalScore field value if set, zero value otherwise.
func (o *JobRequestEmergencyCandidate) GetTotalScore() float32 {
	if o == nil || IsNil(o.TotalScore) {
		var ret float32
		return ret
	}
	return *o.TotalScore
}

// GetTotalScoreOk returns a tuple with the TotalScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyCandidate) GetTotalScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalScore) {
		return nil, false
	}
	return o.TotalScore, true
}

// HasTotalScore returns a boolean if a field has been set.
func (o *JobRequestEmergencyCandidate) HasTotalScore() bool {
	if o != nil && !IsNil(o.TotalScore) {
		return true
	}

	return false
}

// SetTotalScore gets a reference to the given float32 and assigns it to the TotalScore field.
func (o *JobRequestEmergencyCandidate) SetTotalScore(v float32) {
	o.TotalScore = &v
}

// GetTravelMinutes returns the TravelMinutes field value if set, zero value otherwise.
func (o *JobRequestEmergencyCandidate) GetTravelMinutes() float32 {
	if o == nil || IsNil(o.TravelMinutes) {
		var ret float32
		return ret
	}
	return *o.TravelMinutes
}

// GetTravelMinutesOk returns a tuple with the TravelMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestEmergencyCandidate) GetTravelMinutesOk() (*float32, bool) {
	if o == nil || IsNil(o.TravelMinutes) {
		return nil, false
	}
	return o.TravelMinutes, true
}

// HasTravelMinutes returns a boolean if a field has been set.
func (o *JobRequestEmergencyCandidate) HasTravelMinutes() bool {
	if o != nil && !IsNil(o.TravelMinutes) {
		return true
	}

	return false
}

// SetTravelMinutes gets a reference to the given float32 and assigns it to the TravelMinutes field.
func (o *JobRequestEmergencyCandidate) SetTravelMinutes(v float32) {
	o.TravelMinutes = &v
}

func (o JobRequestEmergencyCandidate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestEmergencyCandidate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BookedMinutes) {
		toSerialize["booked_minutes"] = o.BookedMinutes
	}
	if !IsNil(o.Days) {
		toSerialize["days"] = o.Days
	}
	if !IsNil(o.DistanceKm) {
		toSerialize["distance_km"] = o.DistanceKm
	}
	if !IsNil(o.FullName) {
		toSerialize["full_name"] = o.FullName
	}
	if !IsNil(o.MatchedSkills) {
		toSerialize["matched_skills"] = o.MatchedSkills
	}
	if !IsNil(o.TechnicianId) {
		toSerialize["technician_id"] = o.TechnicianId
	}
	if !IsNil(o.TotalMoves) {
		toSerialize["total_moves"] = o.TotalMoves
	}
	if !IsNil(o.TotalScore) {
		toSerialize["total_score"] = o.TotalScore
	}
	if !IsNil(o.TravelMinutes) {
		toSerialize["travel_minutes"] = o.TravelMinutes
	}
	return toSerialize, nil
}

type NullableJobRequestEmergencyCandidate struct {
	value *JobRequestEmergencyCandidate
	isSet bool
}

func (v NullableJobRequestEmergencyCandidate) Get() *JobRequestEmergencyCandidate {
	return v.value
}

func (v *NullableJobRequestEmergencyCandidate) Set(val *JobRequestEmergencyCandidate) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestEmergencyCandidate) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestEmergencyCandidate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestEmergencyCandidate(val *JobRequestEmergencyCandidate) *NullableJobRequestEmergencyCandidate {
	return &NullableJobRequestEmergencyCandidate{value: val, isSet: true}
}

func (v NullableJobRequestEmergencyCandidate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestEmergencyCandidate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


