/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the JobRequestCrewMemberInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestCrewMemberInput{}

// JobRequestCrewMemberInput struct for JobRequestCrewMemberInput
type JobRequestCrewMemberInput struct {
	// Whether this slot is the crew lead. Exactly one slot must set it.
	IsLead *bool `json:"is_lead,omitempty"`
	// UUIDs of the skills this slot requires (hard filter for the matching engine). Optional; up to 20.
	SkillIds []string `json:"skill_ids,omitempty"`
	// This slot's share of the job's man-hours, in percent (1–100). Shares across all slots must sum to 100.
	WrenchPercent *int32 `json:"wrench_percent,omitempty"`
}

// NewJobRequestCrewMemberInput instantiates a new JobRequestCrewMemberInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestCrewMemberInput() *JobRequestCrewMemberInput {
	this := JobRequestCrewMemberInput{}
	return &this
}

// NewJobRequestCrewMemberInputWithDefaults instantiates a new JobRequestCrewMemberInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestCrewMemberInputWithDefaults() *JobRequestCrewMemberInput {
	this := JobRequestCrewMemberInput{}
	return &this
}

// GetIsLead returns the IsLead field value if set, zero value otherwise.
func (o *JobRequestCrewMemberInput) GetIsLead() bool {
	if o == nil || IsNil(o.IsLead) {
		var ret bool
		return ret
	}
	return *o.IsLead
}

// GetIsLeadOk returns a tuple with the IsLead field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestCrewMemberInput) GetIsLeadOk() (*bool, bool) {
	if o == nil || IsNil(o.IsLead) {
		return nil, false
	}
	return o.IsLead, true
}

// HasIsLead returns a boolean if a field has been set.
func (o *JobRequestCrewMemberInput) HasIsLead() bool {
	if o != nil && !IsNil(o.IsLead) {
		return true
	}

	return false
}

// SetIsLead gets a reference to the given bool and assigns it to the IsLead field.
func (o *JobRequestCrewMemberInput) SetIsLead(v bool) {
	o.IsLead = &v
}

// GetSkillIds returns the SkillIds field value if set, zero value otherwise.
func (o *JobRequestCrewMemberInput) GetSkillIds() []string {
	if o == nil || IsNil(o.SkillIds) {
		var ret []string
		return ret
	}
	return o.SkillIds
}

// GetSkillIdsOk returns a tuple with the SkillIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestCrewMemberInput) GetSkillIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SkillIds) {
		return nil, false
	}
	return o.SkillIds, true
}

// HasSkillIds returns a boolean if a field has been set.
func (o *JobRequestCrewMemberInput) HasSkillIds() bool {
	if o != nil && !IsNil(o.SkillIds) {
		return true
	}

	return false
}

// SetSkillIds gets a reference to the given []string and assigns it to the SkillIds field.
func (o *JobRequestCrewMemberInput) SetSkillIds(v []string) {
	o.SkillIds = v
}

// GetWrenchPercent returns the WrenchPercent field value if set, zero value otherwise.
func (o *JobRequestCrewMemberInput) GetWrenchPercent() int32 {
	if o == nil || IsNil(o.WrenchPercent) {
		var ret int32
		return ret
	}
	return *o.WrenchPercent
}

// GetWrenchPercentOk returns a tuple with the WrenchPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestCrewMemberInput) GetWrenchPercentOk() (*int32, bool) {
	if o == nil || IsNil(o.WrenchPercent) {
		return nil, false
	}
	return o.WrenchPercent, true
}

// HasWrenchPercent returns a boolean if a field has been set.
func (o *JobRequestCrewMemberInput) HasWrenchPercent() bool {
	if o != nil && !IsNil(o.WrenchPercent) {
		return true
	}

	return false
}

// SetWrenchPercent gets a reference to the given int32 and assigns it to the WrenchPercent field.
func (o *JobRequestCrewMemberInput) SetWrenchPercent(v int32) {
	o.WrenchPercent = &v
}

func (o JobRequestCrewMemberInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestCrewMemberInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsLead) {
		toSerialize["is_lead"] = o.IsLead
	}
	if !IsNil(o.SkillIds) {
		toSerialize["skill_ids"] = o.SkillIds
	}
	if !IsNil(o.WrenchPercent) {
		toSerialize["wrench_percent"] = o.WrenchPercent
	}
	return toSerialize, nil
}

type NullableJobRequestCrewMemberInput struct {
	value *JobRequestCrewMemberInput
	isSet bool
}

func (v NullableJobRequestCrewMemberInput) Get() *JobRequestCrewMemberInput {
	return v.value
}

func (v *NullableJobRequestCrewMemberInput) Set(val *JobRequestCrewMemberInput) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestCrewMemberInput) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestCrewMemberInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestCrewMemberInput(val *JobRequestCrewMemberInput) *NullableJobRequestCrewMemberInput {
	return &NullableJobRequestCrewMemberInput{value: val, isSet: true}
}

func (v NullableJobRequestCrewMemberInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestCrewMemberInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


