/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the JobRequestCrewCandidates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestCrewCandidates{}

// JobRequestCrewCandidates struct for JobRequestCrewCandidates
type JobRequestCrewCandidates struct {
	// Job identifier — the human-readable short code when present, else the job UUID.
	JobRequestId *string `json:"job_request_id,omitempty"`
	// Ranked feasible lead technicians, best total_score first; each carries its own buddy/vehicle sections when requested.
	Leads []JobRequestLeadCandidate `json:"leads,omitempty"`
}

// NewJobRequestCrewCandidates instantiates a new JobRequestCrewCandidates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestCrewCandidates() *JobRequestCrewCandidates {
	this := JobRequestCrewCandidates{}
	return &this
}

// NewJobRequestCrewCandidatesWithDefaults instantiates a new JobRequestCrewCandidates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestCrewCandidatesWithDefaults() *JobRequestCrewCandidates {
	this := JobRequestCrewCandidates{}
	return &this
}

// GetJobRequestId returns the JobRequestId field value if set, zero value otherwise.
func (o *JobRequestCrewCandidates) GetJobRequestId() string {
	if o == nil || IsNil(o.JobRequestId) {
		var ret string
		return ret
	}
	return *o.JobRequestId
}

// GetJobRequestIdOk returns a tuple with the JobRequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestCrewCandidates) GetJobRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobRequestId) {
		return nil, false
	}
	return o.JobRequestId, true
}

// HasJobRequestId returns a boolean if a field has been set.
func (o *JobRequestCrewCandidates) HasJobRequestId() bool {
	if o != nil && !IsNil(o.JobRequestId) {
		return true
	}

	return false
}

// SetJobRequestId gets a reference to the given string and assigns it to the JobRequestId field.
func (o *JobRequestCrewCandidates) SetJobRequestId(v string) {
	o.JobRequestId = &v
}

// GetLeads returns the Leads field value if set, zero value otherwise.
func (o *JobRequestCrewCandidates) GetLeads() []JobRequestLeadCandidate {
	if o == nil || IsNil(o.Leads) {
		var ret []JobRequestLeadCandidate
		return ret
	}
	return o.Leads
}

// GetLeadsOk returns a tuple with the Leads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestCrewCandidates) GetLeadsOk() ([]JobRequestLeadCandidate, bool) {
	if o == nil || IsNil(o.Leads) {
		return nil, false
	}
	return o.Leads, true
}

// HasLeads returns a boolean if a field has been set.
func (o *JobRequestCrewCandidates) HasLeads() bool {
	if o != nil && !IsNil(o.Leads) {
		return true
	}

	return false
}

// SetLeads gets a reference to the given []JobRequestLeadCandidate and assigns it to the Leads field.
func (o *JobRequestCrewCandidates) SetLeads(v []JobRequestLeadCandidate) {
	o.Leads = v
}

func (o JobRequestCrewCandidates) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestCrewCandidates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobRequestId) {
		toSerialize["job_request_id"] = o.JobRequestId
	}
	if !IsNil(o.Leads) {
		toSerialize["leads"] = o.Leads
	}
	return toSerialize, nil
}

type NullableJobRequestCrewCandidates struct {
	value *JobRequestCrewCandidates
	isSet bool
}

func (v NullableJobRequestCrewCandidates) Get() *JobRequestCrewCandidates {
	return v.value
}

func (v *NullableJobRequestCrewCandidates) Set(val *JobRequestCrewCandidates) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestCrewCandidates) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestCrewCandidates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestCrewCandidates(val *JobRequestCrewCandidates) *NullableJobRequestCrewCandidates {
	return &NullableJobRequestCrewCandidates{value: val, isSet: true}
}

func (v NullableJobRequestCrewCandidates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestCrewCandidates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


