/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the JobRequestList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestList{}

// JobRequestList struct for JobRequestList
type JobRequestList struct {
	// The job requests on this page.
	Items []JobRequest `json:"items,omitempty"`
	// Page/limit/total pagination metadata.
	Meta *Pagination `json:"meta,omitempty"`
}

// NewJobRequestList instantiates a new JobRequestList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestList() *JobRequestList {
	this := JobRequestList{}
	return &this
}

// NewJobRequestListWithDefaults instantiates a new JobRequestList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestListWithDefaults() *JobRequestList {
	this := JobRequestList{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *JobRequestList) GetItems() []JobRequest {
	if o == nil || IsNil(o.Items) {
		var ret []JobRequest
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestList) GetItemsOk() ([]JobRequest, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *JobRequestList) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []JobRequest and assigns it to the Items field.
func (o *JobRequestList) SetItems(v []JobRequest) {
	o.Items = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *JobRequestList) GetMeta() Pagination {
	if o == nil || IsNil(o.Meta) {
		var ret Pagination
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestList) GetMetaOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *JobRequestList) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given Pagination and assigns it to the Meta field.
func (o *JobRequestList) SetMeta(v Pagination) {
	o.Meta = &v
}

func (o JobRequestList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableJobRequestList struct {
	value *JobRequestList
	isSet bool
}

func (v NullableJobRequestList) Get() *JobRequestList {
	return v.value
}

func (v *NullableJobRequestList) Set(val *JobRequestList) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestList) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestList(val *JobRequestList) *NullableJobRequestList {
	return &NullableJobRequestList{value: val, isSet: true}
}

func (v NullableJobRequestList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


