/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the JobRequestAssignedVehicle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestAssignedVehicle{}

// JobRequestAssignedVehicle struct for JobRequestAssignedVehicle
type JobRequestAssignedVehicle struct {
	// Vehicle UUID.
	Id *string `json:"id,omitempty"`
	// Vehicle display name.
	Name *string `json:"name,omitempty"`
}

// NewJobRequestAssignedVehicle instantiates a new JobRequestAssignedVehicle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestAssignedVehicle() *JobRequestAssignedVehicle {
	this := JobRequestAssignedVehicle{}
	return &this
}

// NewJobRequestAssignedVehicleWithDefaults instantiates a new JobRequestAssignedVehicle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestAssignedVehicleWithDefaults() *JobRequestAssignedVehicle {
	this := JobRequestAssignedVehicle{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *JobRequestAssignedVehicle) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestAssignedVehicle) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *JobRequestAssignedVehicle) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *JobRequestAssignedVehicle) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *JobRequestAssignedVehicle) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestAssignedVehicle) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *JobRequestAssignedVehicle) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *JobRequestAssignedVehicle) SetName(v string) {
	o.Name = &v
}

func (o JobRequestAssignedVehicle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestAssignedVehicle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableJobRequestAssignedVehicle struct {
	value *JobRequestAssignedVehicle
	isSet bool
}

func (v NullableJobRequestAssignedVehicle) Get() *JobRequestAssignedVehicle {
	return v.value
}

func (v *NullableJobRequestAssignedVehicle) Set(val *JobRequestAssignedVehicle) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestAssignedVehicle) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestAssignedVehicle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestAssignedVehicle(val *JobRequestAssignedVehicle) *NullableJobRequestAssignedVehicle {
	return &NullableJobRequestAssignedVehicle{value: val, isSet: true}
}

func (v NullableJobRequestAssignedVehicle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestAssignedVehicle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


