/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobRequestQuoteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestQuoteRequest{}

// JobRequestQuoteRequest struct for JobRequestQuoteRequest
type JobRequestQuoteRequest struct {
	// Crew — multi-person plan (tech lead + buddies). Omit / empty = single person (lead 100%). When present must have exactly one is_lead and wrench_percent summing to 100. See MULTIPERSON_CREW_DESIGN.md.
	Crew []JobRequestCrewMemberInput `json:"crew,omitempty"`
	// Demobilization (teardown) minutes added after the work. Optional, min 0.
	DemobilizationMinutes *int32 `json:"demobilization_minutes,omitempty"`
	// Hands-on work duration in minutes (man-minutes for a crew job). Required, min 1.
	JobDurationMinutes int32 `json:"job_duration_minutes"`
	// Mobilization (setup/travel-prep) minutes added before the work. Optional, min 0.
	MobilizationMinutes *int32 `json:"mobilization_minutes,omitempty"`
	// Optimistic-lock fence: the status_version from your last read. Omitted/0 = fence on the row's current version (no race protection).
	StatusVersion *int32 `json:"status_version,omitempty"`
}

type _JobRequestQuoteRequest JobRequestQuoteRequest

// NewJobRequestQuoteRequest instantiates a new JobRequestQuoteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestQuoteRequest(jobDurationMinutes int32) *JobRequestQuoteRequest {
	this := JobRequestQuoteRequest{}
	this.JobDurationMinutes = jobDurationMinutes
	return &this
}

// NewJobRequestQuoteRequestWithDefaults instantiates a new JobRequestQuoteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestQuoteRequestWithDefaults() *JobRequestQuoteRequest {
	this := JobRequestQuoteRequest{}
	return &this
}

// GetCrew returns the Crew field value if set, zero value otherwise.
func (o *JobRequestQuoteRequest) GetCrew() []JobRequestCrewMemberInput {
	if o == nil || IsNil(o.Crew) {
		var ret []JobRequestCrewMemberInput
		return ret
	}
	return o.Crew
}

// GetCrewOk returns a tuple with the Crew field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestQuoteRequest) GetCrewOk() ([]JobRequestCrewMemberInput, bool) {
	if o == nil || IsNil(o.Crew) {
		return nil, false
	}
	return o.Crew, true
}

// HasCrew returns a boolean if a field has been set.
func (o *JobRequestQuoteRequest) HasCrew() bool {
	if o != nil && !IsNil(o.Crew) {
		return true
	}

	return false
}

// SetCrew gets a reference to the given []JobRequestCrewMemberInput and assigns it to the Crew field.
func (o *JobRequestQuoteRequest) SetCrew(v []JobRequestCrewMemberInput) {
	o.Crew = v
}

// GetDemobilizationMinutes returns the DemobilizationMinutes field value if set, zero value otherwise.
func (o *JobRequestQuoteRequest) GetDemobilizationMinutes() int32 {
	if o == nil || IsNil(o.DemobilizationMinutes) {
		var ret int32
		return ret
	}
	return *o.DemobilizationMinutes
}

// GetDemobilizationMinutesOk returns a tuple with the DemobilizationMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestQuoteRequest) GetDemobilizationMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.DemobilizationMinutes) {
		return nil, false
	}
	return o.DemobilizationMinutes, true
}

// HasDemobilizationMinutes returns a boolean if a field has been set.
func (o *JobRequestQuoteRequest) HasDemobilizationMinutes() bool {
	if o != nil && !IsNil(o.DemobilizationMinutes) {
		return true
	}

	return false
}

// SetDemobilizationMinutes gets a reference to the given int32 and assigns it to the DemobilizationMinutes field.
func (o *JobRequestQuoteRequest) SetDemobilizationMinutes(v int32) {
	o.DemobilizationMinutes = &v
}

// GetJobDurationMinutes returns the JobDurationMinutes field value
func (o *JobRequestQuoteRequest) GetJobDurationMinutes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.JobDurationMinutes
}

// GetJobDurationMinutesOk returns a tuple with the JobDurationMinutes field value
// and a boolean to check if the value has been set.
func (o *JobRequestQuoteRequest) GetJobDurationMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobDurationMinutes, true
}

// SetJobDurationMinutes sets field value
func (o *JobRequestQuoteRequest) SetJobDurationMinutes(v int32) {
	o.JobDurationMinutes = v
}

// GetMobilizationMinutes returns the MobilizationMinutes field value if set, zero value otherwise.
func (o *JobRequestQuoteRequest) GetMobilizationMinutes() int32 {
	if o == nil || IsNil(o.MobilizationMinutes) {
		var ret int32
		return ret
	}
	return *o.MobilizationMinutes
}

// GetMobilizationMinutesOk returns a tuple with the MobilizationMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestQuoteRequest) GetMobilizationMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.MobilizationMinutes) {
		return nil, false
	}
	return o.MobilizationMinutes, true
}

// HasMobilizationMinutes returns a boolean if a field has been set.
func (o *JobRequestQuoteRequest) HasMobilizationMinutes() bool {
	if o != nil && !IsNil(o.MobilizationMinutes) {
		return true
	}

	return false
}

// SetMobilizationMinutes gets a reference to the given int32 and assigns it to the MobilizationMinutes field.
func (o *JobRequestQuoteRequest) SetMobilizationMinutes(v int32) {
	o.MobilizationMinutes = &v
}

// GetStatusVersion returns the StatusVersion field value if set, zero value otherwise.
func (o *JobRequestQuoteRequest) GetStatusVersion() int32 {
	if o == nil || IsNil(o.StatusVersion) {
		var ret int32
		return ret
	}
	return *o.StatusVersion
}

// GetStatusVersionOk returns a tuple with the StatusVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestQuoteRequest) GetStatusVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusVersion) {
		return nil, false
	}
	return o.StatusVersion, true
}

// HasStatusVersion returns a boolean if a field has been set.
func (o *JobRequestQuoteRequest) HasStatusVersion() bool {
	if o != nil && !IsNil(o.StatusVersion) {
		return true
	}

	return false
}

// SetStatusVersion gets a reference to the given int32 and assigns it to the StatusVersion field.
func (o *JobRequestQuoteRequest) SetStatusVersion(v int32) {
	o.StatusVersion = &v
}

func (o JobRequestQuoteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestQuoteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Crew) {
		toSerialize["crew"] = o.Crew
	}
	if !IsNil(o.DemobilizationMinutes) {
		toSerialize["demobilization_minutes"] = o.DemobilizationMinutes
	}
	toSerialize["job_duration_minutes"] = o.JobDurationMinutes
	if !IsNil(o.MobilizationMinutes) {
		toSerialize["mobilization_minutes"] = o.MobilizationMinutes
	}
	if !IsNil(o.StatusVersion) {
		toSerialize["status_version"] = o.StatusVersion
	}
	return toSerialize, nil
}

func (o *JobRequestQuoteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_duration_minutes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobRequestQuoteRequest := _JobRequestQuoteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobRequestQuoteRequest)

	if err != nil {
		return err
	}

	*o = JobRequestQuoteRequest(varJobRequestQuoteRequest)

	return err
}

type NullableJobRequestQuoteRequest struct {
	value *JobRequestQuoteRequest
	isSet bool
}

func (v NullableJobRequestQuoteRequest) Get() *JobRequestQuoteRequest {
	return v.value
}

func (v *NullableJobRequestQuoteRequest) Set(val *JobRequestQuoteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestQuoteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestQuoteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestQuoteRequest(val *JobRequestQuoteRequest) *NullableJobRequestQuoteRequest {
	return &NullableJobRequestQuoteRequest{value: val, isSet: true}
}

func (v NullableJobRequestQuoteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestQuoteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


