/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
	"time"
)

// checks if the JobRequestSession type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestSession{}

// JobRequestSession struct for JobRequestSession
type JobRequestSession struct {
	// Calendar day (YYYY-MM-DD) this session falls on, business-local.
	Date *string `json:"date,omitempty"`
	// Leave-home time bracketing the day: StartAt minus planned travel (UTC). Omitted (with return_at) when travel is unknown.
	DepartAt *time.Time `json:"depart_at,omitempty"`
	// Leave site — end of demobilization (UTC).
	EndAt *time.Time `json:"end_at,omitempty"`
	// 1-based day index within the job's span (1 for single-day jobs).
	Ordinal *int32 `json:"ordinal,omitempty"`
	// Arrive-home time bracketing the day: EndAt plus planned travel (UTC). Omitted (with depart_at) when travel is unknown.
	ReturnAt *time.Time `json:"return_at,omitempty"`
	// On-site arrival — start of mobilization (UTC).
	StartAt *time.Time `json:"start_at,omitempty"`
	// TravelMinutes is the PLANNED one-way commute (home → site) for this day, snapshotted at assignment. Omitted when unknown (admin-fallback job with no geocoded location, or legacy row).
	TravelMinutes *int32 `json:"travel_minutes,omitempty"`
}

// NewJobRequestSession instantiates a new JobRequestSession object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestSession() *JobRequestSession {
	this := JobRequestSession{}
	return &this
}

// NewJobRequestSessionWithDefaults instantiates a new JobRequestSession object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestSessionWithDefaults() *JobRequestSession {
	this := JobRequestSession{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *JobRequestSession) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSession) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *JobRequestSession) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *JobRequestSession) SetDate(v string) {
	o.Date = &v
}

// GetDepartAt returns the DepartAt field value if set, zero value otherwise.
func (o *JobRequestSession) GetDepartAt() time.Time {
	if o == nil || IsNil(o.DepartAt) {
		var ret time.Time
		return ret
	}
	return *o.DepartAt
}

// GetDepartAtOk returns a tuple with the DepartAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSession) GetDepartAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DepartAt) {
		return nil, false
	}
	return o.DepartAt, true
}

// HasDepartAt returns a boolean if a field has been set.
func (o *JobRequestSession) HasDepartAt() bool {
	if o != nil && !IsNil(o.DepartAt) {
		return true
	}

	return false
}

// SetDepartAt gets a reference to the given time.Time and assigns it to the DepartAt field.
func (o *JobRequestSession) SetDepartAt(v time.Time) {
	o.DepartAt = &v
}

// GetEndAt returns the EndAt field value if set, zero value otherwise.
func (o *JobRequestSession) GetEndAt() time.Time {
	if o == nil || IsNil(o.EndAt) {
		var ret time.Time
		return ret
	}
	return *o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSession) GetEndAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndAt) {
		return nil, false
	}
	return o.EndAt, true
}

// HasEndAt returns a boolean if a field has been set.
func (o *JobRequestSession) HasEndAt() bool {
	if o != nil && !IsNil(o.EndAt) {
		return true
	}

	return false
}

// SetEndAt gets a reference to the given time.Time and assigns it to the EndAt field.
func (o *JobRequestSession) SetEndAt(v time.Time) {
	o.EndAt = &v
}

// GetOrdinal returns the Ordinal field value if set, zero value otherwise.
func (o *JobRequestSession) GetOrdinal() int32 {
	if o == nil || IsNil(o.Ordinal) {
		var ret int32
		return ret
	}
	return *o.Ordinal
}

// GetOrdinalOk returns a tuple with the Ordinal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSession) GetOrdinalOk() (*int32, bool) {
	if o == nil || IsNil(o.Ordinal) {
		return nil, false
	}
	return o.Ordinal, true
}

// HasOrdinal returns a boolean if a field has been set.
func (o *JobRequestSession) HasOrdinal() bool {
	if o != nil && !IsNil(o.Ordinal) {
		return true
	}

	return false
}

// SetOrdinal gets a reference to the given int32 and assigns it to the Ordinal field.
func (o *JobRequestSession) SetOrdinal(v int32) {
	o.Ordinal = &v
}

// GetReturnAt returns the ReturnAt field value if set, zero value otherwise.
func (o *JobRequestSession) GetReturnAt() time.Time {
	if o == nil || IsNil(o.ReturnAt) {
		var ret time.Time
		return ret
	}
	return *o.ReturnAt
}

// GetReturnAtOk returns a tuple with the ReturnAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSession) GetReturnAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ReturnAt) {
		return nil, false
	}
	return o.ReturnAt, true
}

// HasReturnAt returns a boolean if a field has been set.
func (o *JobRequestSession) HasReturnAt() bool {
	if o != nil && !IsNil(o.ReturnAt) {
		return true
	}

	return false
}

// SetReturnAt gets a reference to the given time.Time and assigns it to the ReturnAt field.
func (o *JobRequestSession) SetReturnAt(v time.Time) {
	o.ReturnAt = &v
}

// GetStartAt returns the StartAt field value if set, zero value otherwise.
func (o *JobRequestSession) GetStartAt() time.Time {
	if o == nil || IsNil(o.StartAt) {
		var ret time.Time
		return ret
	}
	return *o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSession) GetStartAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartAt) {
		return nil, false
	}
	return o.StartAt, true
}

// HasStartAt returns a boolean if a field has been set.
func (o *JobRequestSession) HasStartAt() bool {
	if o != nil && !IsNil(o.StartAt) {
		return true
	}

	return false
}

// SetStartAt gets a reference to the given time.Time and assigns it to the StartAt field.
func (o *JobRequestSession) SetStartAt(v time.Time) {
	o.StartAt = &v
}

// GetTravelMinutes returns the TravelMinutes field value if set, zero value otherwise.
func (o *JobRequestSession) GetTravelMinutes() int32 {
	if o == nil || IsNil(o.TravelMinutes) {
		var ret int32
		return ret
	}
	return *o.TravelMinutes
}

// GetTravelMinutesOk returns a tuple with the TravelMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSession) GetTravelMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.TravelMinutes) {
		return nil, false
	}
	return o.TravelMinutes, true
}

// HasTravelMinutes returns a boolean if a field has been set.
func (o *JobRequestSession) HasTravelMinutes() bool {
	if o != nil && !IsNil(o.TravelMinutes) {
		return true
	}

	return false
}

// SetTravelMinutes gets a reference to the given int32 and assigns it to the TravelMinutes field.
func (o *JobRequestSession) SetTravelMinutes(v int32) {
	o.TravelMinutes = &v
}

func (o JobRequestSession) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestSession) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.DepartAt) {
		toSerialize["depart_at"] = o.DepartAt
	}
	if !IsNil(o.EndAt) {
		toSerialize["end_at"] = o.EndAt
	}
	if !IsNil(o.Ordinal) {
		toSerialize["ordinal"] = o.Ordinal
	}
	if !IsNil(o.ReturnAt) {
		toSerialize["return_at"] = o.ReturnAt
	}
	if !IsNil(o.StartAt) {
		toSerialize["start_at"] = o.StartAt
	}
	if !IsNil(o.TravelMinutes) {
		toSerialize["travel_minutes"] = o.TravelMinutes
	}
	return toSerialize, nil
}

type NullableJobRequestSession struct {
	value *JobRequestSession
	isSet bool
}

func (v NullableJobRequestSession) Get() *JobRequestSession {
	return v.value
}

func (v *NullableJobRequestSession) Set(val *JobRequestSession) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestSession) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestSession) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestSession(val *JobRequestSession) *NullableJobRequestSession {
	return &NullableJobRequestSession{value: val, isSet: true}
}

func (v NullableJobRequestSession) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestSession) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


