/*
CrispHive Developer API

Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
	"time"
)

// checks if the JobRequestDayWindows type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestDayWindows{}

// JobRequestDayWindows struct for JobRequestDayWindows
type JobRequestDayWindows struct {
	// Calendar day (YYYY-MM-DD), customer-local.
	Date *time.Time `json:"date,omitempty"`
	// Available time-of-day periods on this day.
	Periods []JobRequestPeriod `json:"periods,omitempty"`
}

// NewJobRequestDayWindows instantiates a new JobRequestDayWindows object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestDayWindows() *JobRequestDayWindows {
	this := JobRequestDayWindows{}
	return &this
}

// NewJobRequestDayWindowsWithDefaults instantiates a new JobRequestDayWindows object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestDayWindowsWithDefaults() *JobRequestDayWindows {
	this := JobRequestDayWindows{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *JobRequestDayWindows) GetDate() time.Time {
	if o == nil || IsNil(o.Date) {
		var ret time.Time
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestDayWindows) GetDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *JobRequestDayWindows) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given time.Time and assigns it to the Date field.
func (o *JobRequestDayWindows) SetDate(v time.Time) {
	o.Date = &v
}

// GetPeriods returns the Periods field value if set, zero value otherwise.
func (o *JobRequestDayWindows) GetPeriods() []JobRequestPeriod {
	if o == nil || IsNil(o.Periods) {
		var ret []JobRequestPeriod
		return ret
	}
	return o.Periods
}

// GetPeriodsOk returns a tuple with the Periods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestDayWindows) GetPeriodsOk() ([]JobRequestPeriod, bool) {
	if o == nil || IsNil(o.Periods) {
		return nil, false
	}
	return o.Periods, true
}

// HasPeriods returns a boolean if a field has been set.
func (o *JobRequestDayWindows) HasPeriods() bool {
	if o != nil && !IsNil(o.Periods) {
		return true
	}

	return false
}

// SetPeriods gets a reference to the given []JobRequestPeriod and assigns it to the Periods field.
func (o *JobRequestDayWindows) SetPeriods(v []JobRequestPeriod) {
	o.Periods = v
}

func (o JobRequestDayWindows) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestDayWindows) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Periods) {
		toSerialize["periods"] = o.Periods
	}
	return toSerialize, nil
}

type NullableJobRequestDayWindows struct {
	value *JobRequestDayWindows
	isSet bool
}

func (v NullableJobRequestDayWindows) Get() *JobRequestDayWindows {
	return v.value
}

func (v *NullableJobRequestDayWindows) Set(val *JobRequestDayWindows) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestDayWindows) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestDayWindows) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestDayWindows(val *JobRequestDayWindows) *NullableJobRequestDayWindows {
	return &NullableJobRequestDayWindows{value: val, isSet: true}
}

func (v NullableJobRequestDayWindows) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestDayWindows) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


