/*
CrispHive Developer API

Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the Customer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Customer{}

// Customer struct for Customer
type Customer struct {
	// Contact details: address, phone, email, preferred technician, service area.
	Contact *CustomerContact `json:"contact,omitempty"`
	// Core identity and lifecycle fields.
	Profile *CustomerProfile `json:"profile,omitempty"`
	// Spending aggregates over the trailing 12 months.
	Spending *CustomerSpending `json:"spending,omitempty"`
}

// NewCustomer instantiates a new Customer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomer() *Customer {
	this := Customer{}
	return &this
}

// NewCustomerWithDefaults instantiates a new Customer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerWithDefaults() *Customer {
	this := Customer{}
	return &this
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *Customer) GetContact() CustomerContact {
	if o == nil || IsNil(o.Contact) {
		var ret CustomerContact
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customer) GetContactOk() (*CustomerContact, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *Customer) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given CustomerContact and assigns it to the Contact field.
func (o *Customer) SetContact(v CustomerContact) {
	o.Contact = &v
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *Customer) GetProfile() CustomerProfile {
	if o == nil || IsNil(o.Profile) {
		var ret CustomerProfile
		return ret
	}
	return *o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customer) GetProfileOk() (*CustomerProfile, bool) {
	if o == nil || IsNil(o.Profile) {
		return nil, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *Customer) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given CustomerProfile and assigns it to the Profile field.
func (o *Customer) SetProfile(v CustomerProfile) {
	o.Profile = &v
}

// GetSpending returns the Spending field value if set, zero value otherwise.
func (o *Customer) GetSpending() CustomerSpending {
	if o == nil || IsNil(o.Spending) {
		var ret CustomerSpending
		return ret
	}
	return *o.Spending
}

// GetSpendingOk returns a tuple with the Spending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customer) GetSpendingOk() (*CustomerSpending, bool) {
	if o == nil || IsNil(o.Spending) {
		return nil, false
	}
	return o.Spending, true
}

// HasSpending returns a boolean if a field has been set.
func (o *Customer) HasSpending() bool {
	if o != nil && !IsNil(o.Spending) {
		return true
	}

	return false
}

// SetSpending gets a reference to the given CustomerSpending and assigns it to the Spending field.
func (o *Customer) SetSpending(v CustomerSpending) {
	o.Spending = &v
}

func (o Customer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Customer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	if !IsNil(o.Spending) {
		toSerialize["spending"] = o.Spending
	}
	return toSerialize, nil
}

type NullableCustomer struct {
	value *Customer
	isSet bool
}

func (v NullableCustomer) Get() *Customer {
	return v.value
}

func (v *NullableCustomer) Set(val *Customer) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomer) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomer(val *Customer) *NullableCustomer {
	return &NullableCustomer{value: val, isSet: true}
}

func (v NullableCustomer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


