/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the JobRequestActionAuditBy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestActionAuditBy{}

// JobRequestActionAuditBy struct for JobRequestActionAuditBy
type JobRequestActionAuditBy struct {
	// Role that fired the action (business_on_behalf = a business user acting for the customer/technician).
	Actor *string `json:"actor,omitempty"`
	// UUID of the firing user; null for an unauthenticated customer actor.
	UserId *string `json:"user_id,omitempty"`
}

// NewJobRequestActionAuditBy instantiates a new JobRequestActionAuditBy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestActionAuditBy() *JobRequestActionAuditBy {
	this := JobRequestActionAuditBy{}
	return &this
}

// NewJobRequestActionAuditByWithDefaults instantiates a new JobRequestActionAuditBy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestActionAuditByWithDefaults() *JobRequestActionAuditBy {
	this := JobRequestActionAuditBy{}
	return &this
}

// GetActor returns the Actor field value if set, zero value otherwise.
func (o *JobRequestActionAuditBy) GetActor() string {
	if o == nil || IsNil(o.Actor) {
		var ret string
		return ret
	}
	return *o.Actor
}

// GetActorOk returns a tuple with the Actor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestActionAuditBy) GetActorOk() (*string, bool) {
	if o == nil || IsNil(o.Actor) {
		return nil, false
	}
	return o.Actor, true
}

// HasActor returns a boolean if a field has been set.
func (o *JobRequestActionAuditBy) HasActor() bool {
	if o != nil && !IsNil(o.Actor) {
		return true
	}

	return false
}

// SetActor gets a reference to the given string and assigns it to the Actor field.
func (o *JobRequestActionAuditBy) SetActor(v string) {
	o.Actor = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *JobRequestActionAuditBy) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestActionAuditBy) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *JobRequestActionAuditBy) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *JobRequestActionAuditBy) SetUserId(v string) {
	o.UserId = &v
}

func (o JobRequestActionAuditBy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestActionAuditBy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Actor) {
		toSerialize["actor"] = o.Actor
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	return toSerialize, nil
}

type NullableJobRequestActionAuditBy struct {
	value *JobRequestActionAuditBy
	isSet bool
}

func (v NullableJobRequestActionAuditBy) Get() *JobRequestActionAuditBy {
	return v.value
}

func (v *NullableJobRequestActionAuditBy) Set(val *JobRequestActionAuditBy) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestActionAuditBy) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestActionAuditBy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestActionAuditBy(val *JobRequestActionAuditBy) *NullableJobRequestActionAuditBy {
	return &NullableJobRequestActionAuditBy{value: val, isSet: true}
}

func (v NullableJobRequestActionAuditBy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestActionAuditBy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


