/*
CrispHive Developer API

Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
	"time"
)

// checks if the JobRequestTimelineAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestTimelineAction{}

// JobRequestTimelineAction struct for JobRequestTimelineAction
type JobRequestTimelineAction struct {
	// Role expected to fire this action (badge hint, NOT who actually fired it).
	Actor *string `json:"actor,omitempty"`
	// When the action was fired (UTC); null until fired.
	FiredAt *time.Time `json:"fired_at,omitempty"`
	// Action key (e.g. quote, confirm_booking, complete, or a DYNAMIC action).
	Key *string `json:"key,omitempty"`
	// Action label, resolved to the request locale.
	Label *string `json:"label,omitempty"`
	// Payload mirrors action_data[key].payload — raw JSON; `swaggertype` hints the swag CLI which doesn't natively know json.RawMessage.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Where this action sits relative to the job's progress.
	State *string `json:"state,omitempty"`
}

// NewJobRequestTimelineAction instantiates a new JobRequestTimelineAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestTimelineAction() *JobRequestTimelineAction {
	this := JobRequestTimelineAction{}
	return &this
}

// NewJobRequestTimelineActionWithDefaults instantiates a new JobRequestTimelineAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestTimelineActionWithDefaults() *JobRequestTimelineAction {
	this := JobRequestTimelineAction{}
	return &this
}

// GetActor returns the Actor field value if set, zero value otherwise.
func (o *JobRequestTimelineAction) GetActor() string {
	if o == nil || IsNil(o.Actor) {
		var ret string
		return ret
	}
	return *o.Actor
}

// GetActorOk returns a tuple with the Actor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimelineAction) GetActorOk() (*string, bool) {
	if o == nil || IsNil(o.Actor) {
		return nil, false
	}
	return o.Actor, true
}

// HasActor returns a boolean if a field has been set.
func (o *JobRequestTimelineAction) HasActor() bool {
	if o != nil && !IsNil(o.Actor) {
		return true
	}

	return false
}

// SetActor gets a reference to the given string and assigns it to the Actor field.
func (o *JobRequestTimelineAction) SetActor(v string) {
	o.Actor = &v
}

// GetFiredAt returns the FiredAt field value if set, zero value otherwise.
func (o *JobRequestTimelineAction) GetFiredAt() time.Time {
	if o == nil || IsNil(o.FiredAt) {
		var ret time.Time
		return ret
	}
	return *o.FiredAt
}

// GetFiredAtOk returns a tuple with the FiredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimelineAction) GetFiredAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FiredAt) {
		return nil, false
	}
	return o.FiredAt, true
}

// HasFiredAt returns a boolean if a field has been set.
func (o *JobRequestTimelineAction) HasFiredAt() bool {
	if o != nil && !IsNil(o.FiredAt) {
		return true
	}

	return false
}

// SetFiredAt gets a reference to the given time.Time and assigns it to the FiredAt field.
func (o *JobRequestTimelineAction) SetFiredAt(v time.Time) {
	o.FiredAt = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *JobRequestTimelineAction) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimelineAction) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *JobRequestTimelineAction) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *JobRequestTimelineAction) SetKey(v string) {
	o.Key = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *JobRequestTimelineAction) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimelineAction) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *JobRequestTimelineAction) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *JobRequestTimelineAction) SetLabel(v string) {
	o.Label = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *JobRequestTimelineAction) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimelineAction) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *JobRequestTimelineAction) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *JobRequestTimelineAction) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *JobRequestTimelineAction) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimelineAction) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *JobRequestTimelineAction) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *JobRequestTimelineAction) SetState(v string) {
	o.State = &v
}

func (o JobRequestTimelineAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestTimelineAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Actor) {
		toSerialize["actor"] = o.Actor
	}
	if !IsNil(o.FiredAt) {
		toSerialize["fired_at"] = o.FiredAt
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableJobRequestTimelineAction struct {
	value *JobRequestTimelineAction
	isSet bool
}

func (v NullableJobRequestTimelineAction) Get() *JobRequestTimelineAction {
	return v.value
}

func (v *NullableJobRequestTimelineAction) Set(val *JobRequestTimelineAction) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestTimelineAction) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestTimelineAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestTimelineAction(val *JobRequestTimelineAction) *NullableJobRequestTimelineAction {
	return &NullableJobRequestTimelineAction{value: val, isSet: true}
}

func (v NullableJobRequestTimelineAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestTimelineAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


