/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the JobRequestTimeSegmentsBusinessTime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestTimeSegmentsBusinessTime{}

// JobRequestTimeSegmentsBusinessTime struct for JobRequestTimeSegmentsBusinessTime
type JobRequestTimeSegmentsBusinessTime struct {
	// Calendar day of the window start, business-local (YYYY-MM-DD).
	Date *string `json:"date,omitempty"`
	// Window start as a naive business-local datetime (no UTC offset) — the exact value to send back as scheduled_at on confirm.
	Datetime *string `json:"datetime,omitempty"`
	// Full weekday name of the window start, business-local.
	DayName *string `json:"day_name,omitempty"`
	// Arrival-window start, HH:MM business-local.
	Time *string `json:"time,omitempty"`
	// Arrival-window end, HH:MM business-local.
	TimeEnd *string `json:"time_end,omitempty"`
	// Period bucket of the window start, business-local: 1=morning, 2=afternoon, 3=evening.
	TimePeriod *int32 `json:"time_period,omitempty"`
	// Localized label for time_period.
	TimePeriodLabel *string `json:"time_period_label,omitempty"`
}

// NewJobRequestTimeSegmentsBusinessTime instantiates a new JobRequestTimeSegmentsBusinessTime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestTimeSegmentsBusinessTime() *JobRequestTimeSegmentsBusinessTime {
	this := JobRequestTimeSegmentsBusinessTime{}
	return &this
}

// NewJobRequestTimeSegmentsBusinessTimeWithDefaults instantiates a new JobRequestTimeSegmentsBusinessTime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestTimeSegmentsBusinessTimeWithDefaults() *JobRequestTimeSegmentsBusinessTime {
	this := JobRequestTimeSegmentsBusinessTime{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsBusinessTime) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsBusinessTime) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsBusinessTime) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *JobRequestTimeSegmentsBusinessTime) SetDate(v string) {
	o.Date = &v
}

// GetDatetime returns the Datetime field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsBusinessTime) GetDatetime() string {
	if o == nil || IsNil(o.Datetime) {
		var ret string
		return ret
	}
	return *o.Datetime
}

// GetDatetimeOk returns a tuple with the Datetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsBusinessTime) GetDatetimeOk() (*string, bool) {
	if o == nil || IsNil(o.Datetime) {
		return nil, false
	}
	return o.Datetime, true
}

// HasDatetime returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsBusinessTime) HasDatetime() bool {
	if o != nil && !IsNil(o.Datetime) {
		return true
	}

	return false
}

// SetDatetime gets a reference to the given string and assigns it to the Datetime field.
func (o *JobRequestTimeSegmentsBusinessTime) SetDatetime(v string) {
	o.Datetime = &v
}

// GetDayName returns the DayName field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsBusinessTime) GetDayName() string {
	if o == nil || IsNil(o.DayName) {
		var ret string
		return ret
	}
	return *o.DayName
}

// GetDayNameOk returns a tuple with the DayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsBusinessTime) GetDayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DayName) {
		return nil, false
	}
	return o.DayName, true
}

// HasDayName returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsBusinessTime) HasDayName() bool {
	if o != nil && !IsNil(o.DayName) {
		return true
	}

	return false
}

// SetDayName gets a reference to the given string and assigns it to the DayName field.
func (o *JobRequestTimeSegmentsBusinessTime) SetDayName(v string) {
	o.DayName = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsBusinessTime) GetTime() string {
	if o == nil || IsNil(o.Time) {
		var ret string
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsBusinessTime) GetTimeOk() (*string, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsBusinessTime) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given string and assigns it to the Time field.
func (o *JobRequestTimeSegmentsBusinessTime) SetTime(v string) {
	o.Time = &v
}

// GetTimeEnd returns the TimeEnd field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsBusinessTime) GetTimeEnd() string {
	if o == nil || IsNil(o.TimeEnd) {
		var ret string
		return ret
	}
	return *o.TimeEnd
}

// GetTimeEndOk returns a tuple with the TimeEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsBusinessTime) GetTimeEndOk() (*string, bool) {
	if o == nil || IsNil(o.TimeEnd) {
		return nil, false
	}
	return o.TimeEnd, true
}

// HasTimeEnd returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsBusinessTime) HasTimeEnd() bool {
	if o != nil && !IsNil(o.TimeEnd) {
		return true
	}

	return false
}

// SetTimeEnd gets a reference to the given string and assigns it to the TimeEnd field.
func (o *JobRequestTimeSegmentsBusinessTime) SetTimeEnd(v string) {
	o.TimeEnd = &v
}

// GetTimePeriod returns the TimePeriod field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsBusinessTime) GetTimePeriod() int32 {
	if o == nil || IsNil(o.TimePeriod) {
		var ret int32
		return ret
	}
	return *o.TimePeriod
}

// GetTimePeriodOk returns a tuple with the TimePeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsBusinessTime) GetTimePeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.TimePeriod) {
		return nil, false
	}
	return o.TimePeriod, true
}

// HasTimePeriod returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsBusinessTime) HasTimePeriod() bool {
	if o != nil && !IsNil(o.TimePeriod) {
		return true
	}

	return false
}

// SetTimePeriod gets a reference to the given int32 and assigns it to the TimePeriod field.
func (o *JobRequestTimeSegmentsBusinessTime) SetTimePeriod(v int32) {
	o.TimePeriod = &v
}

// GetTimePeriodLabel returns the TimePeriodLabel field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsBusinessTime) GetTimePeriodLabel() string {
	if o == nil || IsNil(o.TimePeriodLabel) {
		var ret string
		return ret
	}
	return *o.TimePeriodLabel
}

// GetTimePeriodLabelOk returns a tuple with the TimePeriodLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsBusinessTime) GetTimePeriodLabelOk() (*string, bool) {
	if o == nil || IsNil(o.TimePeriodLabel) {
		return nil, false
	}
	return o.TimePeriodLabel, true
}

// HasTimePeriodLabel returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsBusinessTime) HasTimePeriodLabel() bool {
	if o != nil && !IsNil(o.TimePeriodLabel) {
		return true
	}

	return false
}

// SetTimePeriodLabel gets a reference to the given string and assigns it to the TimePeriodLabel field.
func (o *JobRequestTimeSegmentsBusinessTime) SetTimePeriodLabel(v string) {
	o.TimePeriodLabel = &v
}

func (o JobRequestTimeSegmentsBusinessTime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestTimeSegmentsBusinessTime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Datetime) {
		toSerialize["datetime"] = o.Datetime
	}
	if !IsNil(o.DayName) {
		toSerialize["day_name"] = o.DayName
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.TimeEnd) {
		toSerialize["time_end"] = o.TimeEnd
	}
	if !IsNil(o.TimePeriod) {
		toSerialize["time_period"] = o.TimePeriod
	}
	if !IsNil(o.TimePeriodLabel) {
		toSerialize["time_period_label"] = o.TimePeriodLabel
	}
	return toSerialize, nil
}

type NullableJobRequestTimeSegmentsBusinessTime struct {
	value *JobRequestTimeSegmentsBusinessTime
	isSet bool
}

func (v NullableJobRequestTimeSegmentsBusinessTime) Get() *JobRequestTimeSegmentsBusinessTime {
	return v.value
}

func (v *NullableJobRequestTimeSegmentsBusinessTime) Set(val *JobRequestTimeSegmentsBusinessTime) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestTimeSegmentsBusinessTime) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestTimeSegmentsBusinessTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestTimeSegmentsBusinessTime(val *JobRequestTimeSegmentsBusinessTime) *NullableJobRequestTimeSegmentsBusinessTime {
	return &NullableJobRequestTimeSegmentsBusinessTime{value: val, isSet: true}
}

func (v NullableJobRequestTimeSegmentsBusinessTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestTimeSegmentsBusinessTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


