/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
	"time"
)

// checks if the JobRequestRescheduleReassignment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestRescheduleReassignment{}

// JobRequestRescheduleReassignment struct for JobRequestRescheduleReassignment
type JobRequestRescheduleReassignment struct {
	// Name of the reassigned job's customer.
	CustomerName *string `json:"customer_name,omitempty"`
	// The job's UNCHANGED window end (UTC).
	EndAt *time.Time `json:"end_at,omitempty"`
	// UUID of the technician losing the job.
	FromTechnicianId *string `json:"from_technician_id,omitempty"`
	// UUID of the reassigned job.
	JobId *string `json:"job_id,omitempty"`
	// Priority of the reassigned job (p0..p3).
	Priority *string `json:"priority,omitempty"`
	// Human-friendly short code of the reassigned job.
	ShortCode *string `json:"short_code,omitempty"`
	// The job's UNCHANGED window start (UTC) — reassign preserves the customer's slot.
	StartAt *time.Time `json:"start_at,omitempty"`
	// Full name of the receiving technician. Omitted when unresolved.
	ToName *string `json:"to_name,omitempty"`
	// UUID of the alternate technician receiving the job.
	ToTechnicianId *string `json:"to_technician_id,omitempty"`
	// The alternate technician's one-way commute estimate in minutes (engine, rounded up). Omitted when the engine has no location for them.
	TravelMinutes *int32 `json:"travel_minutes,omitempty"`
}

// NewJobRequestRescheduleReassignment instantiates a new JobRequestRescheduleReassignment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestRescheduleReassignment() *JobRequestRescheduleReassignment {
	this := JobRequestRescheduleReassignment{}
	return &this
}

// NewJobRequestRescheduleReassignmentWithDefaults instantiates a new JobRequestRescheduleReassignment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestRescheduleReassignmentWithDefaults() *JobRequestRescheduleReassignment {
	this := JobRequestRescheduleReassignment{}
	return &this
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise.
func (o *JobRequestRescheduleReassignment) GetCustomerName() string {
	if o == nil || IsNil(o.CustomerName) {
		var ret string
		return ret
	}
	return *o.CustomerName
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestRescheduleReassignment) GetCustomerNameOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerName) {
		return nil, false
	}
	return o.CustomerName, true
}

// HasCustomerName returns a boolean if a field has been set.
func (o *JobRequestRescheduleReassignment) HasCustomerName() bool {
	if o != nil && !IsNil(o.CustomerName) {
		return true
	}

	return false
}

// SetCustomerName gets a reference to the given string and assigns it to the CustomerName field.
func (o *JobRequestRescheduleReassignment) SetCustomerName(v string) {
	o.CustomerName = &v
}

// GetEndAt returns the EndAt field value if set, zero value otherwise.
func (o *JobRequestRescheduleReassignment) GetEndAt() time.Time {
	if o == nil || IsNil(o.EndAt) {
		var ret time.Time
		return ret
	}
	return *o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestRescheduleReassignment) GetEndAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndAt) {
		return nil, false
	}
	return o.EndAt, true
}

// HasEndAt returns a boolean if a field has been set.
func (o *JobRequestRescheduleReassignment) HasEndAt() bool {
	if o != nil && !IsNil(o.EndAt) {
		return true
	}

	return false
}

// SetEndAt gets a reference to the given time.Time and assigns it to the EndAt field.
func (o *JobRequestRescheduleReassignment) SetEndAt(v time.Time) {
	o.EndAt = &v
}

// GetFromTechnicianId returns the FromTechnicianId field value if set, zero value otherwise.
func (o *JobRequestRescheduleReassignment) GetFromTechnicianId() string {
	if o == nil || IsNil(o.FromTechnicianId) {
		var ret string
		return ret
	}
	return *o.FromTechnicianId
}

// GetFromTechnicianIdOk returns a tuple with the FromTechnicianId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestRescheduleReassignment) GetFromTechnicianIdOk() (*string, bool) {
	if o == nil || IsNil(o.FromTechnicianId) {
		return nil, false
	}
	return o.FromTechnicianId, true
}

// HasFromTechnicianId returns a boolean if a field has been set.
func (o *JobRequestRescheduleReassignment) HasFromTechnicianId() bool {
	if o != nil && !IsNil(o.FromTechnicianId) {
		return true
	}

	return false
}

// SetFromTechnicianId gets a reference to the given string and assigns it to the FromTechnicianId field.
func (o *JobRequestRescheduleReassignment) SetFromTechnicianId(v string) {
	o.FromTechnicianId = &v
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *JobRequestRescheduleReassignment) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestRescheduleReassignment) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *JobRequestRescheduleReassignment) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *JobRequestRescheduleReassignment) SetJobId(v string) {
	o.JobId = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *JobRequestRescheduleReassignment) GetPriority() string {
	if o == nil || IsNil(o.Priority) {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestRescheduleReassignment) GetPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *JobRequestRescheduleReassignment) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *JobRequestRescheduleReassignment) SetPriority(v string) {
	o.Priority = &v
}

// GetShortCode returns the ShortCode field value if set, zero value otherwise.
func (o *JobRequestRescheduleReassignment) GetShortCode() string {
	if o == nil || IsNil(o.ShortCode) {
		var ret string
		return ret
	}
	return *o.ShortCode
}

// GetShortCodeOk returns a tuple with the ShortCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestRescheduleReassignment) GetShortCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ShortCode) {
		return nil, false
	}
	return o.ShortCode, true
}

// HasShortCode returns a boolean if a field has been set.
func (o *JobRequestRescheduleReassignment) HasShortCode() bool {
	if o != nil && !IsNil(o.ShortCode) {
		return true
	}

	return false
}

// SetShortCode gets a reference to the given string and assigns it to the ShortCode field.
func (o *JobRequestRescheduleReassignment) SetShortCode(v string) {
	o.ShortCode = &v
}

// GetStartAt returns the StartAt field value if set, zero value otherwise.
func (o *JobRequestRescheduleReassignment) GetStartAt() time.Time {
	if o == nil || IsNil(o.StartAt) {
		var ret time.Time
		return ret
	}
	return *o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestRescheduleReassignment) GetStartAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartAt) {
		return nil, false
	}
	return o.StartAt, true
}

// HasStartAt returns a boolean if a field has been set.
func (o *JobRequestRescheduleReassignment) HasStartAt() bool {
	if o != nil && !IsNil(o.StartAt) {
		return true
	}

	return false
}

// SetStartAt gets a reference to the given time.Time and assigns it to the StartAt field.
func (o *JobRequestRescheduleReassignment) SetStartAt(v time.Time) {
	o.StartAt = &v
}

// GetToName returns the ToName field value if set, zero value otherwise.
func (o *JobRequestRescheduleReassignment) GetToName() string {
	if o == nil || IsNil(o.ToName) {
		var ret string
		return ret
	}
	return *o.ToName
}

// GetToNameOk returns a tuple with the ToName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestRescheduleReassignment) GetToNameOk() (*string, bool) {
	if o == nil || IsNil(o.ToName) {
		return nil, false
	}
	return o.ToName, true
}

// HasToName returns a boolean if a field has been set.
func (o *JobRequestRescheduleReassignment) HasToName() bool {
	if o != nil && !IsNil(o.ToName) {
		return true
	}

	return false
}

// SetToName gets a reference to the given string and assigns it to the ToName field.
func (o *JobRequestRescheduleReassignment) SetToName(v string) {
	o.ToName = &v
}

// GetToTechnicianId returns the ToTechnicianId field value if set, zero value otherwise.
func (o *JobRequestRescheduleReassignment) GetToTechnicianId() string {
	if o == nil || IsNil(o.ToTechnicianId) {
		var ret string
		return ret
	}
	return *o.ToTechnicianId
}

// GetToTechnicianIdOk returns a tuple with the ToTechnicianId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestRescheduleReassignment) GetToTechnicianIdOk() (*string, bool) {
	if o == nil || IsNil(o.ToTechnicianId) {
		return nil, false
	}
	return o.ToTechnicianId, true
}

// HasToTechnicianId returns a boolean if a field has been set.
func (o *JobRequestRescheduleReassignment) HasToTechnicianId() bool {
	if o != nil && !IsNil(o.ToTechnicianId) {
		return true
	}

	return false
}

// SetToTechnicianId gets a reference to the given string and assigns it to the ToTechnicianId field.
func (o *JobRequestRescheduleReassignment) SetToTechnicianId(v string) {
	o.ToTechnicianId = &v
}

// GetTravelMinutes returns the TravelMinutes field value if set, zero value otherwise.
func (o *JobRequestRescheduleReassignment) GetTravelMinutes() int32 {
	if o == nil || IsNil(o.TravelMinutes) {
		var ret int32
		return ret
	}
	return *o.TravelMinutes
}

// GetTravelMinutesOk returns a tuple with the TravelMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestRescheduleReassignment) GetTravelMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.TravelMinutes) {
		return nil, false
	}
	return o.TravelMinutes, true
}

// HasTravelMinutes returns a boolean if a field has been set.
func (o *JobRequestRescheduleReassignment) HasTravelMinutes() bool {
	if o != nil && !IsNil(o.TravelMinutes) {
		return true
	}

	return false
}

// SetTravelMinutes gets a reference to the given int32 and assigns it to the TravelMinutes field.
func (o *JobRequestRescheduleReassignment) SetTravelMinutes(v int32) {
	o.TravelMinutes = &v
}

func (o JobRequestRescheduleReassignment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestRescheduleReassignment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerName) {
		toSerialize["customer_name"] = o.CustomerName
	}
	if !IsNil(o.EndAt) {
		toSerialize["end_at"] = o.EndAt
	}
	if !IsNil(o.FromTechnicianId) {
		toSerialize["from_technician_id"] = o.FromTechnicianId
	}
	if !IsNil(o.JobId) {
		toSerialize["job_id"] = o.JobId
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.ShortCode) {
		toSerialize["short_code"] = o.ShortCode
	}
	if !IsNil(o.StartAt) {
		toSerialize["start_at"] = o.StartAt
	}
	if !IsNil(o.ToName) {
		toSerialize["to_name"] = o.ToName
	}
	if !IsNil(o.ToTechnicianId) {
		toSerialize["to_technician_id"] = o.ToTechnicianId
	}
	if !IsNil(o.TravelMinutes) {
		toSerialize["travel_minutes"] = o.TravelMinutes
	}
	return toSerialize, nil
}

type NullableJobRequestRescheduleReassignment struct {
	value *JobRequestRescheduleReassignment
	isSet bool
}

func (v NullableJobRequestRescheduleReassignment) Get() *JobRequestRescheduleReassignment {
	return v.value
}

func (v *NullableJobRequestRescheduleReassignment) Set(val *JobRequestRescheduleReassignment) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestRescheduleReassignment) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestRescheduleReassignment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestRescheduleReassignment(val *JobRequestRescheduleReassignment) *NullableJobRequestRescheduleReassignment {
	return &NullableJobRequestRescheduleReassignment{value: val, isSet: true}
}

func (v NullableJobRequestRescheduleReassignment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestRescheduleReassignment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


