/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobRequestCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestCreateRequest{}

// JobRequestCreateRequest struct for JobRequestCreateRequest
type JobRequestCreateRequest struct {
	// UUID of an existing customer of this business to book the job for. Required.
	CustomerId string `json:"customer_id"`
	// Free-text description of the work requested. Optional; max 2000 chars.
	Description *string `json:"description,omitempty"`
	// Requested date(s) + period(s) the customer wants the job. At least one, up to 12.
	JobDates []JobRequestJobDateRequest `json:"job_dates"`
	// UUID of the job type to classify this job. Optional; null leaves the job unclassified.
	JobTypeId *string `json:"job_type_id,omitempty"`
	// Scheduling priority. Optional; omitted bookings receive the business's default_priority setting (assignment settings, default p2). p0=emergency (interrupt-driven insert), p1=top (displaced only by p0), p2=standard, p3=deferrable (first candidate for displacement).
	Priority *string `json:"priority,omitempty"`
	// UUIDs of the skills the customer desires for this job. Optional; up to 20.
	SkillIds []string `json:"skill_ids,omitempty"`
	// SLA deadline (business-local naive datetime, e.g. \"2030-06-14T17:00:00\"). Optional; ONLY valid together with priority=p1 — arms the auto-escalation clock (the job escalates to p0 as breach risk crosses the business's safety buffer). Must be in the future.
	SlaDeadline *string `json:"sla_deadline,omitempty"`
}

type _JobRequestCreateRequest JobRequestCreateRequest

// NewJobRequestCreateRequest instantiates a new JobRequestCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestCreateRequest(customerId string, jobDates []JobRequestJobDateRequest) *JobRequestCreateRequest {
	this := JobRequestCreateRequest{}
	this.CustomerId = customerId
	this.JobDates = jobDates
	return &this
}

// NewJobRequestCreateRequestWithDefaults instantiates a new JobRequestCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestCreateRequestWithDefaults() *JobRequestCreateRequest {
	this := JobRequestCreateRequest{}
	return &this
}

// GetCustomerId returns the CustomerId field value
func (o *JobRequestCreateRequest) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *JobRequestCreateRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *JobRequestCreateRequest) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *JobRequestCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *JobRequestCreateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *JobRequestCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetJobDates returns the JobDates field value
func (o *JobRequestCreateRequest) GetJobDates() []JobRequestJobDateRequest {
	if o == nil {
		var ret []JobRequestJobDateRequest
		return ret
	}

	return o.JobDates
}

// GetJobDatesOk returns a tuple with the JobDates field value
// and a boolean to check if the value has been set.
func (o *JobRequestCreateRequest) GetJobDatesOk() ([]JobRequestJobDateRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.JobDates, true
}

// SetJobDates sets field value
func (o *JobRequestCreateRequest) SetJobDates(v []JobRequestJobDateRequest) {
	o.JobDates = v
}

// GetJobTypeId returns the JobTypeId field value if set, zero value otherwise.
func (o *JobRequestCreateRequest) GetJobTypeId() string {
	if o == nil || IsNil(o.JobTypeId) {
		var ret string
		return ret
	}
	return *o.JobTypeId
}

// GetJobTypeIdOk returns a tuple with the JobTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestCreateRequest) GetJobTypeIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobTypeId) {
		return nil, false
	}
	return o.JobTypeId, true
}

// HasJobTypeId returns a boolean if a field has been set.
func (o *JobRequestCreateRequest) HasJobTypeId() bool {
	if o != nil && !IsNil(o.JobTypeId) {
		return true
	}

	return false
}

// SetJobTypeId gets a reference to the given string and assigns it to the JobTypeId field.
func (o *JobRequestCreateRequest) SetJobTypeId(v string) {
	o.JobTypeId = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *JobRequestCreateRequest) GetPriority() string {
	if o == nil || IsNil(o.Priority) {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestCreateRequest) GetPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *JobRequestCreateRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *JobRequestCreateRequest) SetPriority(v string) {
	o.Priority = &v
}

// GetSkillIds returns the SkillIds field value if set, zero value otherwise.
func (o *JobRequestCreateRequest) GetSkillIds() []string {
	if o == nil || IsNil(o.SkillIds) {
		var ret []string
		return ret
	}
	return o.SkillIds
}

// GetSkillIdsOk returns a tuple with the SkillIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestCreateRequest) GetSkillIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SkillIds) {
		return nil, false
	}
	return o.SkillIds, true
}

// HasSkillIds returns a boolean if a field has been set.
func (o *JobRequestCreateRequest) HasSkillIds() bool {
	if o != nil && !IsNil(o.SkillIds) {
		return true
	}

	return false
}

// SetSkillIds gets a reference to the given []string and assigns it to the SkillIds field.
func (o *JobRequestCreateRequest) SetSkillIds(v []string) {
	o.SkillIds = v
}

// GetSlaDeadline returns the SlaDeadline field value if set, zero value otherwise.
func (o *JobRequestCreateRequest) GetSlaDeadline() string {
	if o == nil || IsNil(o.SlaDeadline) {
		var ret string
		return ret
	}
	return *o.SlaDeadline
}

// GetSlaDeadlineOk returns a tuple with the SlaDeadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestCreateRequest) GetSlaDeadlineOk() (*string, bool) {
	if o == nil || IsNil(o.SlaDeadline) {
		return nil, false
	}
	return o.SlaDeadline, true
}

// HasSlaDeadline returns a boolean if a field has been set.
func (o *JobRequestCreateRequest) HasSlaDeadline() bool {
	if o != nil && !IsNil(o.SlaDeadline) {
		return true
	}

	return false
}

// SetSlaDeadline gets a reference to the given string and assigns it to the SlaDeadline field.
func (o *JobRequestCreateRequest) SetSlaDeadline(v string) {
	o.SlaDeadline = &v
}

func (o JobRequestCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customer_id"] = o.CustomerId
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["job_dates"] = o.JobDates
	if !IsNil(o.JobTypeId) {
		toSerialize["job_type_id"] = o.JobTypeId
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.SkillIds) {
		toSerialize["skill_ids"] = o.SkillIds
	}
	if !IsNil(o.SlaDeadline) {
		toSerialize["sla_deadline"] = o.SlaDeadline
	}
	return toSerialize, nil
}

func (o *JobRequestCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customer_id",
		"job_dates",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobRequestCreateRequest := _JobRequestCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobRequestCreateRequest)

	if err != nil {
		return err
	}

	*o = JobRequestCreateRequest(varJobRequestCreateRequest)

	return err
}

type NullableJobRequestCreateRequest struct {
	value *JobRequestCreateRequest
	isSet bool
}

func (v NullableJobRequestCreateRequest) Get() *JobRequestCreateRequest {
	return v.value
}

func (v *NullableJobRequestCreateRequest) Set(val *JobRequestCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestCreateRequest(val *JobRequestCreateRequest) *NullableJobRequestCreateRequest {
	return &NullableJobRequestCreateRequest{value: val, isSet: true}
}

func (v NullableJobRequestCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


