/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the CustomerSpending type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerSpending{}

// CustomerSpending struct for CustomerSpending
type CustomerSpending struct {
	// Average value per completed job.
	AvgJobValue *float32 `json:"avg_job_value,omitempty"`
	// ISO 4217 currency code for the monetary fields (e.g. \"USD\", \"CAD\").
	Currency *string `json:"currency,omitempty"`
	// Human-readable rank label (e.g. \"Top 5%\").
	RankPositionLabel *string `json:"rank_position_label,omitempty"`
	// Loyalty tier the spend resolves to.
	Tier *string `json:"tier,omitempty"`
	// Progress toward the next tier.
	TierProgress *CustomerTierProgress `json:"tier_progress,omitempty"`
	// Total amount spent in the trailing 12 months.
	TotalSpent12m *float32 `json:"total_spent_12m,omitempty"`
}

// NewCustomerSpending instantiates a new CustomerSpending object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerSpending() *CustomerSpending {
	this := CustomerSpending{}
	return &this
}

// NewCustomerSpendingWithDefaults instantiates a new CustomerSpending object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerSpendingWithDefaults() *CustomerSpending {
	this := CustomerSpending{}
	return &this
}

// GetAvgJobValue returns the AvgJobValue field value if set, zero value otherwise.
func (o *CustomerSpending) GetAvgJobValue() float32 {
	if o == nil || IsNil(o.AvgJobValue) {
		var ret float32
		return ret
	}
	return *o.AvgJobValue
}

// GetAvgJobValueOk returns a tuple with the AvgJobValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerSpending) GetAvgJobValueOk() (*float32, bool) {
	if o == nil || IsNil(o.AvgJobValue) {
		return nil, false
	}
	return o.AvgJobValue, true
}

// HasAvgJobValue returns a boolean if a field has been set.
func (o *CustomerSpending) HasAvgJobValue() bool {
	if o != nil && !IsNil(o.AvgJobValue) {
		return true
	}

	return false
}

// SetAvgJobValue gets a reference to the given float32 and assigns it to the AvgJobValue field.
func (o *CustomerSpending) SetAvgJobValue(v float32) {
	o.AvgJobValue = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *CustomerSpending) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerSpending) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *CustomerSpending) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *CustomerSpending) SetCurrency(v string) {
	o.Currency = &v
}

// GetRankPositionLabel returns the RankPositionLabel field value if set, zero value otherwise.
func (o *CustomerSpending) GetRankPositionLabel() string {
	if o == nil || IsNil(o.RankPositionLabel) {
		var ret string
		return ret
	}
	return *o.RankPositionLabel
}

// GetRankPositionLabelOk returns a tuple with the RankPositionLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerSpending) GetRankPositionLabelOk() (*string, bool) {
	if o == nil || IsNil(o.RankPositionLabel) {
		return nil, false
	}
	return o.RankPositionLabel, true
}

// HasRankPositionLabel returns a boolean if a field has been set.
func (o *CustomerSpending) HasRankPositionLabel() bool {
	if o != nil && !IsNil(o.RankPositionLabel) {
		return true
	}

	return false
}

// SetRankPositionLabel gets a reference to the given string and assigns it to the RankPositionLabel field.
func (o *CustomerSpending) SetRankPositionLabel(v string) {
	o.RankPositionLabel = &v
}

// GetTier returns the Tier field value if set, zero value otherwise.
func (o *CustomerSpending) GetTier() string {
	if o == nil || IsNil(o.Tier) {
		var ret string
		return ret
	}
	return *o.Tier
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerSpending) GetTierOk() (*string, bool) {
	if o == nil || IsNil(o.Tier) {
		return nil, false
	}
	return o.Tier, true
}

// HasTier returns a boolean if a field has been set.
func (o *CustomerSpending) HasTier() bool {
	if o != nil && !IsNil(o.Tier) {
		return true
	}

	return false
}

// SetTier gets a reference to the given string and assigns it to the Tier field.
func (o *CustomerSpending) SetTier(v string) {
	o.Tier = &v
}

// GetTierProgress returns the TierProgress field value if set, zero value otherwise.
func (o *CustomerSpending) GetTierProgress() CustomerTierProgress {
	if o == nil || IsNil(o.TierProgress) {
		var ret CustomerTierProgress
		return ret
	}
	return *o.TierProgress
}

// GetTierProgressOk returns a tuple with the TierProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerSpending) GetTierProgressOk() (*CustomerTierProgress, bool) {
	if o == nil || IsNil(o.TierProgress) {
		return nil, false
	}
	return o.TierProgress, true
}

// HasTierProgress returns a boolean if a field has been set.
func (o *CustomerSpending) HasTierProgress() bool {
	if o != nil && !IsNil(o.TierProgress) {
		return true
	}

	return false
}

// SetTierProgress gets a reference to the given CustomerTierProgress and assigns it to the TierProgress field.
func (o *CustomerSpending) SetTierProgress(v CustomerTierProgress) {
	o.TierProgress = &v
}

// GetTotalSpent12m returns the TotalSpent12m field value if set, zero value otherwise.
func (o *CustomerSpending) GetTotalSpent12m() float32 {
	if o == nil || IsNil(o.TotalSpent12m) {
		var ret float32
		return ret
	}
	return *o.TotalSpent12m
}

// GetTotalSpent12mOk returns a tuple with the TotalSpent12m field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerSpending) GetTotalSpent12mOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalSpent12m) {
		return nil, false
	}
	return o.TotalSpent12m, true
}

// HasTotalSpent12m returns a boolean if a field has been set.
func (o *CustomerSpending) HasTotalSpent12m() bool {
	if o != nil && !IsNil(o.TotalSpent12m) {
		return true
	}

	return false
}

// SetTotalSpent12m gets a reference to the given float32 and assigns it to the TotalSpent12m field.
func (o *CustomerSpending) SetTotalSpent12m(v float32) {
	o.TotalSpent12m = &v
}

func (o CustomerSpending) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerSpending) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvgJobValue) {
		toSerialize["avg_job_value"] = o.AvgJobValue
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.RankPositionLabel) {
		toSerialize["rank_position_label"] = o.RankPositionLabel
	}
	if !IsNil(o.Tier) {
		toSerialize["tier"] = o.Tier
	}
	if !IsNil(o.TierProgress) {
		toSerialize["tier_progress"] = o.TierProgress
	}
	if !IsNil(o.TotalSpent12m) {
		toSerialize["total_spent_12m"] = o.TotalSpent12m
	}
	return toSerialize, nil
}

type NullableCustomerSpending struct {
	value *CustomerSpending
	isSet bool
}

func (v NullableCustomerSpending) Get() *CustomerSpending {
	return v.value
}

func (v *NullableCustomerSpending) Set(val *CustomerSpending) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerSpending) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerSpending) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerSpending(val *CustomerSpending) *NullableCustomerSpending {
	return &NullableCustomerSpending{value: val, isSet: true}
}

func (v NullableCustomerSpending) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerSpending) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


