/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
	"time"
)

// checks if the JobRequestMoveMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestMoveMember{}

// JobRequestMoveMember struct for JobRequestMoveMember
type JobRequestMoveMember struct {
	// This member's planned session end (UTC).
	EndAt *time.Time `json:"end_at,omitempty"`
	// Crew-plan slot order (0 = lead).
	Ordinal *int32 `json:"ordinal,omitempty"`
	// Crew role at the new time.
	Role *string `json:"role,omitempty"`
	// This member's planned session start (UTC).
	StartAt *time.Time `json:"start_at,omitempty"`
	// UUID of the crew member's technician.
	TechnicianId *string `json:"technician_id,omitempty"`
	// One-way commute estimate (minutes, engine, ceil). Omitted = unknown.
	TravelMinutes *int32 `json:"travel_minutes,omitempty"`
}

// NewJobRequestMoveMember instantiates a new JobRequestMoveMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestMoveMember() *JobRequestMoveMember {
	this := JobRequestMoveMember{}
	return &this
}

// NewJobRequestMoveMemberWithDefaults instantiates a new JobRequestMoveMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestMoveMemberWithDefaults() *JobRequestMoveMember {
	this := JobRequestMoveMember{}
	return &this
}

// GetEndAt returns the EndAt field value if set, zero value otherwise.
func (o *JobRequestMoveMember) GetEndAt() time.Time {
	if o == nil || IsNil(o.EndAt) {
		var ret time.Time
		return ret
	}
	return *o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestMoveMember) GetEndAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndAt) {
		return nil, false
	}
	return o.EndAt, true
}

// HasEndAt returns a boolean if a field has been set.
func (o *JobRequestMoveMember) HasEndAt() bool {
	if o != nil && !IsNil(o.EndAt) {
		return true
	}

	return false
}

// SetEndAt gets a reference to the given time.Time and assigns it to the EndAt field.
func (o *JobRequestMoveMember) SetEndAt(v time.Time) {
	o.EndAt = &v
}

// GetOrdinal returns the Ordinal field value if set, zero value otherwise.
func (o *JobRequestMoveMember) GetOrdinal() int32 {
	if o == nil || IsNil(o.Ordinal) {
		var ret int32
		return ret
	}
	return *o.Ordinal
}

// GetOrdinalOk returns a tuple with the Ordinal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestMoveMember) GetOrdinalOk() (*int32, bool) {
	if o == nil || IsNil(o.Ordinal) {
		return nil, false
	}
	return o.Ordinal, true
}

// HasOrdinal returns a boolean if a field has been set.
func (o *JobRequestMoveMember) HasOrdinal() bool {
	if o != nil && !IsNil(o.Ordinal) {
		return true
	}

	return false
}

// SetOrdinal gets a reference to the given int32 and assigns it to the Ordinal field.
func (o *JobRequestMoveMember) SetOrdinal(v int32) {
	o.Ordinal = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *JobRequestMoveMember) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestMoveMember) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *JobRequestMoveMember) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *JobRequestMoveMember) SetRole(v string) {
	o.Role = &v
}

// GetStartAt returns the StartAt field value if set, zero value otherwise.
func (o *JobRequestMoveMember) GetStartAt() time.Time {
	if o == nil || IsNil(o.StartAt) {
		var ret time.Time
		return ret
	}
	return *o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestMoveMember) GetStartAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartAt) {
		return nil, false
	}
	return o.StartAt, true
}

// HasStartAt returns a boolean if a field has been set.
func (o *JobRequestMoveMember) HasStartAt() bool {
	if o != nil && !IsNil(o.StartAt) {
		return true
	}

	return false
}

// SetStartAt gets a reference to the given time.Time and assigns it to the StartAt field.
func (o *JobRequestMoveMember) SetStartAt(v time.Time) {
	o.StartAt = &v
}

// GetTechnicianId returns the TechnicianId field value if set, zero value otherwise.
func (o *JobRequestMoveMember) GetTechnicianId() string {
	if o == nil || IsNil(o.TechnicianId) {
		var ret string
		return ret
	}
	return *o.TechnicianId
}

// GetTechnicianIdOk returns a tuple with the TechnicianId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestMoveMember) GetTechnicianIdOk() (*string, bool) {
	if o == nil || IsNil(o.TechnicianId) {
		return nil, false
	}
	return o.TechnicianId, true
}

// HasTechnicianId returns a boolean if a field has been set.
func (o *JobRequestMoveMember) HasTechnicianId() bool {
	if o != nil && !IsNil(o.TechnicianId) {
		return true
	}

	return false
}

// SetTechnicianId gets a reference to the given string and assigns it to the TechnicianId field.
func (o *JobRequestMoveMember) SetTechnicianId(v string) {
	o.TechnicianId = &v
}

// GetTravelMinutes returns the TravelMinutes field value if set, zero value otherwise.
func (o *JobRequestMoveMember) GetTravelMinutes() int32 {
	if o == nil || IsNil(o.TravelMinutes) {
		var ret int32
		return ret
	}
	return *o.TravelMinutes
}

// GetTravelMinutesOk returns a tuple with the TravelMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestMoveMember) GetTravelMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.TravelMinutes) {
		return nil, false
	}
	return o.TravelMinutes, true
}

// HasTravelMinutes returns a boolean if a field has been set.
func (o *JobRequestMoveMember) HasTravelMinutes() bool {
	if o != nil && !IsNil(o.TravelMinutes) {
		return true
	}

	return false
}

// SetTravelMinutes gets a reference to the given int32 and assigns it to the TravelMinutes field.
func (o *JobRequestMoveMember) SetTravelMinutes(v int32) {
	o.TravelMinutes = &v
}

func (o JobRequestMoveMember) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestMoveMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndAt) {
		toSerialize["end_at"] = o.EndAt
	}
	if !IsNil(o.Ordinal) {
		toSerialize["ordinal"] = o.Ordinal
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.StartAt) {
		toSerialize["start_at"] = o.StartAt
	}
	if !IsNil(o.TechnicianId) {
		toSerialize["technician_id"] = o.TechnicianId
	}
	if !IsNil(o.TravelMinutes) {
		toSerialize["travel_minutes"] = o.TravelMinutes
	}
	return toSerialize, nil
}

type NullableJobRequestMoveMember struct {
	value *JobRequestMoveMember
	isSet bool
}

func (v NullableJobRequestMoveMember) Get() *JobRequestMoveMember {
	return v.value
}

func (v *NullableJobRequestMoveMember) Set(val *JobRequestMoveMember) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestMoveMember) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestMoveMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestMoveMember(val *JobRequestMoveMember) *NullableJobRequestMoveMember {
	return &NullableJobRequestMoveMember{value: val, isSet: true}
}

func (v NullableJobRequestMoveMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestMoveMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


