/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the CommitEmergencyReschedule200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommitEmergencyReschedule200Response{}

// CommitEmergencyReschedule200Response struct for CommitEmergencyReschedule200Response
type CommitEmergencyReschedule200Response struct {
	Data *JobRequestEmergencyPlan `json:"data,omitempty"`
	// 0 on success; a stable string error code (e.g. \"VALIDATION_ERROR\") on failure.
	ErrorCode interface{} `json:"error_code,omitempty"`
	// Field-level validation details; present only for VALIDATION_ERROR responses.
	Errors interface{} `json:"errors,omitempty"`
	// Human-readable message (\"Success\" or an error description), localized via the X-Locale header.
	Message *string `json:"message,omitempty"`
}

// NewCommitEmergencyReschedule200Response instantiates a new CommitEmergencyReschedule200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommitEmergencyReschedule200Response() *CommitEmergencyReschedule200Response {
	this := CommitEmergencyReschedule200Response{}
	return &this
}

// NewCommitEmergencyReschedule200ResponseWithDefaults instantiates a new CommitEmergencyReschedule200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommitEmergencyReschedule200ResponseWithDefaults() *CommitEmergencyReschedule200Response {
	this := CommitEmergencyReschedule200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CommitEmergencyReschedule200Response) GetData() JobRequestEmergencyPlan {
	if o == nil || IsNil(o.Data) {
		var ret JobRequestEmergencyPlan
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommitEmergencyReschedule200Response) GetDataOk() (*JobRequestEmergencyPlan, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CommitEmergencyReschedule200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given JobRequestEmergencyPlan and assigns it to the Data field.
func (o *CommitEmergencyReschedule200Response) SetData(v JobRequestEmergencyPlan) {
	o.Data = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CommitEmergencyReschedule200Response) GetErrorCode() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CommitEmergencyReschedule200Response) GetErrorCodeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return &o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *CommitEmergencyReschedule200Response) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given interface{} and assigns it to the ErrorCode field.
func (o *CommitEmergencyReschedule200Response) SetErrorCode(v interface{}) {
	o.ErrorCode = v
}

// GetErrors returns the Errors field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CommitEmergencyReschedule200Response) GetErrors() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CommitEmergencyReschedule200Response) GetErrorsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return &o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *CommitEmergencyReschedule200Response) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given interface{} and assigns it to the Errors field.
func (o *CommitEmergencyReschedule200Response) SetErrors(v interface{}) {
	o.Errors = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CommitEmergencyReschedule200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommitEmergencyReschedule200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CommitEmergencyReschedule200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CommitEmergencyReschedule200Response) SetMessage(v string) {
	o.Message = &v
}

func (o CommitEmergencyReschedule200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommitEmergencyReschedule200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.ErrorCode != nil {
		toSerialize["error_code"] = o.ErrorCode
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCommitEmergencyReschedule200Response struct {
	value *CommitEmergencyReschedule200Response
	isSet bool
}

func (v NullableCommitEmergencyReschedule200Response) Get() *CommitEmergencyReschedule200Response {
	return v.value
}

func (v *NullableCommitEmergencyReschedule200Response) Set(val *CommitEmergencyReschedule200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCommitEmergencyReschedule200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCommitEmergencyReschedule200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommitEmergencyReschedule200Response(val *CommitEmergencyReschedule200Response) *NullableCommitEmergencyReschedule200Response {
	return &NullableCommitEmergencyReschedule200Response{value: val, isSet: true}
}

func (v NullableCommitEmergencyReschedule200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommitEmergencyReschedule200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


