/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
	"time"
)

// checks if the JobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequest{}

// JobRequest struct for JobRequest
type JobRequest struct {
	// ActionAudit is the per-action audit log keyed by action_key. `complete` fixed action không xuất hiện ở đây — actor lookup qua CompletedByUserID.
	ActionAudit *map[string]JobRequestActionAuditEntry `json:"action_audit,omitempty"`
	// The job's service address snapshot.
	Address *JobRequestAddressSummary `json:"address,omitempty"`
	// The job's archive state.
	Archive *JobRequestArchiveSummary `json:"archive,omitempty"`
	// AssignedVehicle is the carpool vehicle (the lead drives). Omitted when the job has no vehicle.
	AssignedVehicle *JobRequestAssignedVehicle `json:"assigned_vehicle,omitempty"`
	// Who/what is assigned to the job.
	Assignment *JobRequestAssignmentSummary `json:"assignment,omitempty"`
	// Attention is the dispatch-board \"needs attention\" marker (exception tray); null when the job needs no attention.
	Attention *JobRequestAttentionSummary `json:"attention,omitempty"`
	// UUID of the owning business.
	BusinessId *string `json:"business_id,omitempty"`
	// When the job was completed (UTC); null until completed.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// UUID of the user who fired complete; null until completed.
	CompletedByUserId *string `json:"completed_by_user_id,omitempty"`
	// When the job was created (UTC).
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Crew is the multi-person crew on the job (lead first). A single-person job has one member. Omitted when no session plan exists.
	Crew []JobRequestCrewMember `json:"crew,omitempty"`
	// The job's current workflow status.
	CurrentStatus *JobRequestStatusSummary `json:"current_status,omitempty"`
	// The job's customer contact snapshot.
	Customer *JobRequestCustomerSummary `json:"customer,omitempty"`
	// Ready-to-share customer URL embedding the magic token. Omitted if not issued.
	CustomerUrl *string `json:"customer_url,omitempty"`
	// When the job was soft-deleted (UTC); omitted unless deleted.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Free-text job description; null if none.
	Description *string `json:"description,omitempty"`
	// Job request UUID.
	Id *string `json:"id,omitempty"`
	// UUID of the job type, or null if unclassified.
	JobTypeId *string `json:"job_type_id,omitempty"`
	// Job type display name (resolved to locale). Omitted if unclassified.
	JobTypeName *string `json:"job_type_name,omitempty"`
	// The action(s) the job is currently waiting on. Omitted in a terminal status.
	NextActions []JobRequestActionSummary `json:"next_actions,omitempty"`
	// Scheduling priority. p0=emergency (interrupt-driven), p1=top (displaced only by p0), p2=standard, p3=deferrable (first candidate for displacement).
	Priority *string `json:"priority,omitempty"`
	// The time-bundle quoted for the job.
	Quote *JobRequestQuoteSummary `json:"quote,omitempty"`
	// The customer's rating of the completed job.
	Rating *JobRequestRatingSummary `json:"rating,omitempty"`
	// When/how the job is scheduled and its per-day plan.
	Schedule *JobRequestSchedule `json:"schedule,omitempty"`
	// Human-friendly short code. Omitted if not assigned.
	ShortCode *string `json:"short_code,omitempty"`
	// Desired skills for the job (resolved id+name).
	Skills []JobRequestSkillSummary `json:"skills,omitempty"`
	// SLA deadline (UTC) armed on a p1 job; omitted when no SLA.
	SlaDeadline *time.Time `json:"sla_deadline,omitempty"`
	// When the SLA sweep auto-escalated this job to p0 (UTC); omitted if never.
	SlaEscalatedAt *time.Time `json:"sla_escalated_at,omitempty"`
	// When the sweep fired the one-shot pre-escalation warning (UTC); omitted if never.
	SlaWarnedAt *time.Time `json:"sla_warned_at,omitempty"`
	// Optimistic-lock version; pass back as status_version on transitions to avoid races.
	StatusVersion *int32 `json:"status_version,omitempty"`
	// When the job was last modified (UTC).
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// UUID of the workflow snapshot driving this job's state machine.
	WorkflowId *string `json:"workflow_id,omitempty"`
	// Workflow display name.
	WorkflowName *string `json:"workflow_name,omitempty"`
}

// NewJobRequest instantiates a new JobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequest() *JobRequest {
	this := JobRequest{}
	return &this
}

// NewJobRequestWithDefaults instantiates a new JobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestWithDefaults() *JobRequest {
	this := JobRequest{}
	return &this
}

// GetActionAudit returns the ActionAudit field value if set, zero value otherwise.
func (o *JobRequest) GetActionAudit() map[string]JobRequestActionAuditEntry {
	if o == nil || IsNil(o.ActionAudit) {
		var ret map[string]JobRequestActionAuditEntry
		return ret
	}
	return *o.ActionAudit
}

// GetActionAuditOk returns a tuple with the ActionAudit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetActionAuditOk() (*map[string]JobRequestActionAuditEntry, bool) {
	if o == nil || IsNil(o.ActionAudit) {
		return nil, false
	}
	return o.ActionAudit, true
}

// HasActionAudit returns a boolean if a field has been set.
func (o *JobRequest) HasActionAudit() bool {
	if o != nil && !IsNil(o.ActionAudit) {
		return true
	}

	return false
}

// SetActionAudit gets a reference to the given map[string]JobRequestActionAuditEntry and assigns it to the ActionAudit field.
func (o *JobRequest) SetActionAudit(v map[string]JobRequestActionAuditEntry) {
	o.ActionAudit = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *JobRequest) GetAddress() JobRequestAddressSummary {
	if o == nil || IsNil(o.Address) {
		var ret JobRequestAddressSummary
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetAddressOk() (*JobRequestAddressSummary, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *JobRequest) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given JobRequestAddressSummary and assigns it to the Address field.
func (o *JobRequest) SetAddress(v JobRequestAddressSummary) {
	o.Address = &v
}

// GetArchive returns the Archive field value if set, zero value otherwise.
func (o *JobRequest) GetArchive() JobRequestArchiveSummary {
	if o == nil || IsNil(o.Archive) {
		var ret JobRequestArchiveSummary
		return ret
	}
	return *o.Archive
}

// GetArchiveOk returns a tuple with the Archive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetArchiveOk() (*JobRequestArchiveSummary, bool) {
	if o == nil || IsNil(o.Archive) {
		return nil, false
	}
	return o.Archive, true
}

// HasArchive returns a boolean if a field has been set.
func (o *JobRequest) HasArchive() bool {
	if o != nil && !IsNil(o.Archive) {
		return true
	}

	return false
}

// SetArchive gets a reference to the given JobRequestArchiveSummary and assigns it to the Archive field.
func (o *JobRequest) SetArchive(v JobRequestArchiveSummary) {
	o.Archive = &v
}

// GetAssignedVehicle returns the AssignedVehicle field value if set, zero value otherwise.
func (o *JobRequest) GetAssignedVehicle() JobRequestAssignedVehicle {
	if o == nil || IsNil(o.AssignedVehicle) {
		var ret JobRequestAssignedVehicle
		return ret
	}
	return *o.AssignedVehicle
}

// GetAssignedVehicleOk returns a tuple with the AssignedVehicle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetAssignedVehicleOk() (*JobRequestAssignedVehicle, bool) {
	if o == nil || IsNil(o.AssignedVehicle) {
		return nil, false
	}
	return o.AssignedVehicle, true
}

// HasAssignedVehicle returns a boolean if a field has been set.
func (o *JobRequest) HasAssignedVehicle() bool {
	if o != nil && !IsNil(o.AssignedVehicle) {
		return true
	}

	return false
}

// SetAssignedVehicle gets a reference to the given JobRequestAssignedVehicle and assigns it to the AssignedVehicle field.
func (o *JobRequest) SetAssignedVehicle(v JobRequestAssignedVehicle) {
	o.AssignedVehicle = &v
}

// GetAssignment returns the Assignment field value if set, zero value otherwise.
func (o *JobRequest) GetAssignment() JobRequestAssignmentSummary {
	if o == nil || IsNil(o.Assignment) {
		var ret JobRequestAssignmentSummary
		return ret
	}
	return *o.Assignment
}

// GetAssignmentOk returns a tuple with the Assignment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetAssignmentOk() (*JobRequestAssignmentSummary, bool) {
	if o == nil || IsNil(o.Assignment) {
		return nil, false
	}
	return o.Assignment, true
}

// HasAssignment returns a boolean if a field has been set.
func (o *JobRequest) HasAssignment() bool {
	if o != nil && !IsNil(o.Assignment) {
		return true
	}

	return false
}

// SetAssignment gets a reference to the given JobRequestAssignmentSummary and assigns it to the Assignment field.
func (o *JobRequest) SetAssignment(v JobRequestAssignmentSummary) {
	o.Assignment = &v
}

// GetAttention returns the Attention field value if set, zero value otherwise.
func (o *JobRequest) GetAttention() JobRequestAttentionSummary {
	if o == nil || IsNil(o.Attention) {
		var ret JobRequestAttentionSummary
		return ret
	}
	return *o.Attention
}

// GetAttentionOk returns a tuple with the Attention field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetAttentionOk() (*JobRequestAttentionSummary, bool) {
	if o == nil || IsNil(o.Attention) {
		return nil, false
	}
	return o.Attention, true
}

// HasAttention returns a boolean if a field has been set.
func (o *JobRequest) HasAttention() bool {
	if o != nil && !IsNil(o.Attention) {
		return true
	}

	return false
}

// SetAttention gets a reference to the given JobRequestAttentionSummary and assigns it to the Attention field.
func (o *JobRequest) SetAttention(v JobRequestAttentionSummary) {
	o.Attention = &v
}

// GetBusinessId returns the BusinessId field value if set, zero value otherwise.
func (o *JobRequest) GetBusinessId() string {
	if o == nil || IsNil(o.BusinessId) {
		var ret string
		return ret
	}
	return *o.BusinessId
}

// GetBusinessIdOk returns a tuple with the BusinessId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetBusinessIdOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessId) {
		return nil, false
	}
	return o.BusinessId, true
}

// HasBusinessId returns a boolean if a field has been set.
func (o *JobRequest) HasBusinessId() bool {
	if o != nil && !IsNil(o.BusinessId) {
		return true
	}

	return false
}

// SetBusinessId gets a reference to the given string and assigns it to the BusinessId field.
func (o *JobRequest) SetBusinessId(v string) {
	o.BusinessId = &v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise.
func (o *JobRequest) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CompletedAt) {
		return nil, false
	}
	return o.CompletedAt, true
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *JobRequest) HasCompletedAt() bool {
	if o != nil && !IsNil(o.CompletedAt) {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given time.Time and assigns it to the CompletedAt field.
func (o *JobRequest) SetCompletedAt(v time.Time) {
	o.CompletedAt = &v
}

// GetCompletedByUserId returns the CompletedByUserId field value if set, zero value otherwise.
func (o *JobRequest) GetCompletedByUserId() string {
	if o == nil || IsNil(o.CompletedByUserId) {
		var ret string
		return ret
	}
	return *o.CompletedByUserId
}

// GetCompletedByUserIdOk returns a tuple with the CompletedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetCompletedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.CompletedByUserId) {
		return nil, false
	}
	return o.CompletedByUserId, true
}

// HasCompletedByUserId returns a boolean if a field has been set.
func (o *JobRequest) HasCompletedByUserId() bool {
	if o != nil && !IsNil(o.CompletedByUserId) {
		return true
	}

	return false
}

// SetCompletedByUserId gets a reference to the given string and assigns it to the CompletedByUserId field.
func (o *JobRequest) SetCompletedByUserId(v string) {
	o.CompletedByUserId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *JobRequest) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *JobRequest) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *JobRequest) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCrew returns the Crew field value if set, zero value otherwise.
func (o *JobRequest) GetCrew() []JobRequestCrewMember {
	if o == nil || IsNil(o.Crew) {
		var ret []JobRequestCrewMember
		return ret
	}
	return o.Crew
}

// GetCrewOk returns a tuple with the Crew field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetCrewOk() ([]JobRequestCrewMember, bool) {
	if o == nil || IsNil(o.Crew) {
		return nil, false
	}
	return o.Crew, true
}

// HasCrew returns a boolean if a field has been set.
func (o *JobRequest) HasCrew() bool {
	if o != nil && !IsNil(o.Crew) {
		return true
	}

	return false
}

// SetCrew gets a reference to the given []JobRequestCrewMember and assigns it to the Crew field.
func (o *JobRequest) SetCrew(v []JobRequestCrewMember) {
	o.Crew = v
}

// GetCurrentStatus returns the CurrentStatus field value if set, zero value otherwise.
func (o *JobRequest) GetCurrentStatus() JobRequestStatusSummary {
	if o == nil || IsNil(o.CurrentStatus) {
		var ret JobRequestStatusSummary
		return ret
	}
	return *o.CurrentStatus
}

// GetCurrentStatusOk returns a tuple with the CurrentStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetCurrentStatusOk() (*JobRequestStatusSummary, bool) {
	if o == nil || IsNil(o.CurrentStatus) {
		return nil, false
	}
	return o.CurrentStatus, true
}

// HasCurrentStatus returns a boolean if a field has been set.
func (o *JobRequest) HasCurrentStatus() bool {
	if o != nil && !IsNil(o.CurrentStatus) {
		return true
	}

	return false
}

// SetCurrentStatus gets a reference to the given JobRequestStatusSummary and assigns it to the CurrentStatus field.
func (o *JobRequest) SetCurrentStatus(v JobRequestStatusSummary) {
	o.CurrentStatus = &v
}

// GetCustomer returns the Customer field value if set, zero value otherwise.
func (o *JobRequest) GetCustomer() JobRequestCustomerSummary {
	if o == nil || IsNil(o.Customer) {
		var ret JobRequestCustomerSummary
		return ret
	}
	return *o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetCustomerOk() (*JobRequestCustomerSummary, bool) {
	if o == nil || IsNil(o.Customer) {
		return nil, false
	}
	return o.Customer, true
}

// HasCustomer returns a boolean if a field has been set.
func (o *JobRequest) HasCustomer() bool {
	if o != nil && !IsNil(o.Customer) {
		return true
	}

	return false
}

// SetCustomer gets a reference to the given JobRequestCustomerSummary and assigns it to the Customer field.
func (o *JobRequest) SetCustomer(v JobRequestCustomerSummary) {
	o.Customer = &v
}

// GetCustomerUrl returns the CustomerUrl field value if set, zero value otherwise.
func (o *JobRequest) GetCustomerUrl() string {
	if o == nil || IsNil(o.CustomerUrl) {
		var ret string
		return ret
	}
	return *o.CustomerUrl
}

// GetCustomerUrlOk returns a tuple with the CustomerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetCustomerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerUrl) {
		return nil, false
	}
	return o.CustomerUrl, true
}

// HasCustomerUrl returns a boolean if a field has been set.
func (o *JobRequest) HasCustomerUrl() bool {
	if o != nil && !IsNil(o.CustomerUrl) {
		return true
	}

	return false
}

// SetCustomerUrl gets a reference to the given string and assigns it to the CustomerUrl field.
func (o *JobRequest) SetCustomerUrl(v string) {
	o.CustomerUrl = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *JobRequest) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *JobRequest) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *JobRequest) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *JobRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *JobRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *JobRequest) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *JobRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *JobRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *JobRequest) SetId(v string) {
	o.Id = &v
}

// GetJobTypeId returns the JobTypeId field value if set, zero value otherwise.
func (o *JobRequest) GetJobTypeId() string {
	if o == nil || IsNil(o.JobTypeId) {
		var ret string
		return ret
	}
	return *o.JobTypeId
}

// GetJobTypeIdOk returns a tuple with the JobTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetJobTypeIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobTypeId) {
		return nil, false
	}
	return o.JobTypeId, true
}

// HasJobTypeId returns a boolean if a field has been set.
func (o *JobRequest) HasJobTypeId() bool {
	if o != nil && !IsNil(o.JobTypeId) {
		return true
	}

	return false
}

// SetJobTypeId gets a reference to the given string and assigns it to the JobTypeId field.
func (o *JobRequest) SetJobTypeId(v string) {
	o.JobTypeId = &v
}

// GetJobTypeName returns the JobTypeName field value if set, zero value otherwise.
func (o *JobRequest) GetJobTypeName() string {
	if o == nil || IsNil(o.JobTypeName) {
		var ret string
		return ret
	}
	return *o.JobTypeName
}

// GetJobTypeNameOk returns a tuple with the JobTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetJobTypeNameOk() (*string, bool) {
	if o == nil || IsNil(o.JobTypeName) {
		return nil, false
	}
	return o.JobTypeName, true
}

// HasJobTypeName returns a boolean if a field has been set.
func (o *JobRequest) HasJobTypeName() bool {
	if o != nil && !IsNil(o.JobTypeName) {
		return true
	}

	return false
}

// SetJobTypeName gets a reference to the given string and assigns it to the JobTypeName field.
func (o *JobRequest) SetJobTypeName(v string) {
	o.JobTypeName = &v
}

// GetNextActions returns the NextActions field value if set, zero value otherwise.
func (o *JobRequest) GetNextActions() []JobRequestActionSummary {
	if o == nil || IsNil(o.NextActions) {
		var ret []JobRequestActionSummary
		return ret
	}
	return o.NextActions
}

// GetNextActionsOk returns a tuple with the NextActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetNextActionsOk() ([]JobRequestActionSummary, bool) {
	if o == nil || IsNil(o.NextActions) {
		return nil, false
	}
	return o.NextActions, true
}

// HasNextActions returns a boolean if a field has been set.
func (o *JobRequest) HasNextActions() bool {
	if o != nil && !IsNil(o.NextActions) {
		return true
	}

	return false
}

// SetNextActions gets a reference to the given []JobRequestActionSummary and assigns it to the NextActions field.
func (o *JobRequest) SetNextActions(v []JobRequestActionSummary) {
	o.NextActions = v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *JobRequest) GetPriority() string {
	if o == nil || IsNil(o.Priority) {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *JobRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *JobRequest) SetPriority(v string) {
	o.Priority = &v
}

// GetQuote returns the Quote field value if set, zero value otherwise.
func (o *JobRequest) GetQuote() JobRequestQuoteSummary {
	if o == nil || IsNil(o.Quote) {
		var ret JobRequestQuoteSummary
		return ret
	}
	return *o.Quote
}

// GetQuoteOk returns a tuple with the Quote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetQuoteOk() (*JobRequestQuoteSummary, bool) {
	if o == nil || IsNil(o.Quote) {
		return nil, false
	}
	return o.Quote, true
}

// HasQuote returns a boolean if a field has been set.
func (o *JobRequest) HasQuote() bool {
	if o != nil && !IsNil(o.Quote) {
		return true
	}

	return false
}

// SetQuote gets a reference to the given JobRequestQuoteSummary and assigns it to the Quote field.
func (o *JobRequest) SetQuote(v JobRequestQuoteSummary) {
	o.Quote = &v
}

// GetRating returns the Rating field value if set, zero value otherwise.
func (o *JobRequest) GetRating() JobRequestRatingSummary {
	if o == nil || IsNil(o.Rating) {
		var ret JobRequestRatingSummary
		return ret
	}
	return *o.Rating
}

// GetRatingOk returns a tuple with the Rating field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetRatingOk() (*JobRequestRatingSummary, bool) {
	if o == nil || IsNil(o.Rating) {
		return nil, false
	}
	return o.Rating, true
}

// HasRating returns a boolean if a field has been set.
func (o *JobRequest) HasRating() bool {
	if o != nil && !IsNil(o.Rating) {
		return true
	}

	return false
}

// SetRating gets a reference to the given JobRequestRatingSummary and assigns it to the Rating field.
func (o *JobRequest) SetRating(v JobRequestRatingSummary) {
	o.Rating = &v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *JobRequest) GetSchedule() JobRequestSchedule {
	if o == nil || IsNil(o.Schedule) {
		var ret JobRequestSchedule
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetScheduleOk() (*JobRequestSchedule, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *JobRequest) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given JobRequestSchedule and assigns it to the Schedule field.
func (o *JobRequest) SetSchedule(v JobRequestSchedule) {
	o.Schedule = &v
}

// GetShortCode returns the ShortCode field value if set, zero value otherwise.
func (o *JobRequest) GetShortCode() string {
	if o == nil || IsNil(o.ShortCode) {
		var ret string
		return ret
	}
	return *o.ShortCode
}

// GetShortCodeOk returns a tuple with the ShortCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetShortCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ShortCode) {
		return nil, false
	}
	return o.ShortCode, true
}

// HasShortCode returns a boolean if a field has been set.
func (o *JobRequest) HasShortCode() bool {
	if o != nil && !IsNil(o.ShortCode) {
		return true
	}

	return false
}

// SetShortCode gets a reference to the given string and assigns it to the ShortCode field.
func (o *JobRequest) SetShortCode(v string) {
	o.ShortCode = &v
}

// GetSkills returns the Skills field value if set, zero value otherwise.
func (o *JobRequest) GetSkills() []JobRequestSkillSummary {
	if o == nil || IsNil(o.Skills) {
		var ret []JobRequestSkillSummary
		return ret
	}
	return o.Skills
}

// GetSkillsOk returns a tuple with the Skills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetSkillsOk() ([]JobRequestSkillSummary, bool) {
	if o == nil || IsNil(o.Skills) {
		return nil, false
	}
	return o.Skills, true
}

// HasSkills returns a boolean if a field has been set.
func (o *JobRequest) HasSkills() bool {
	if o != nil && !IsNil(o.Skills) {
		return true
	}

	return false
}

// SetSkills gets a reference to the given []JobRequestSkillSummary and assigns it to the Skills field.
func (o *JobRequest) SetSkills(v []JobRequestSkillSummary) {
	o.Skills = v
}

// GetSlaDeadline returns the SlaDeadline field value if set, zero value otherwise.
func (o *JobRequest) GetSlaDeadline() time.Time {
	if o == nil || IsNil(o.SlaDeadline) {
		var ret time.Time
		return ret
	}
	return *o.SlaDeadline
}

// GetSlaDeadlineOk returns a tuple with the SlaDeadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetSlaDeadlineOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SlaDeadline) {
		return nil, false
	}
	return o.SlaDeadline, true
}

// HasSlaDeadline returns a boolean if a field has been set.
func (o *JobRequest) HasSlaDeadline() bool {
	if o != nil && !IsNil(o.SlaDeadline) {
		return true
	}

	return false
}

// SetSlaDeadline gets a reference to the given time.Time and assigns it to the SlaDeadline field.
func (o *JobRequest) SetSlaDeadline(v time.Time) {
	o.SlaDeadline = &v
}

// GetSlaEscalatedAt returns the SlaEscalatedAt field value if set, zero value otherwise.
func (o *JobRequest) GetSlaEscalatedAt() time.Time {
	if o == nil || IsNil(o.SlaEscalatedAt) {
		var ret time.Time
		return ret
	}
	return *o.SlaEscalatedAt
}

// GetSlaEscalatedAtOk returns a tuple with the SlaEscalatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetSlaEscalatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SlaEscalatedAt) {
		return nil, false
	}
	return o.SlaEscalatedAt, true
}

// HasSlaEscalatedAt returns a boolean if a field has been set.
func (o *JobRequest) HasSlaEscalatedAt() bool {
	if o != nil && !IsNil(o.SlaEscalatedAt) {
		return true
	}

	return false
}

// SetSlaEscalatedAt gets a reference to the given time.Time and assigns it to the SlaEscalatedAt field.
func (o *JobRequest) SetSlaEscalatedAt(v time.Time) {
	o.SlaEscalatedAt = &v
}

// GetSlaWarnedAt returns the SlaWarnedAt field value if set, zero value otherwise.
func (o *JobRequest) GetSlaWarnedAt() time.Time {
	if o == nil || IsNil(o.SlaWarnedAt) {
		var ret time.Time
		return ret
	}
	return *o.SlaWarnedAt
}

// GetSlaWarnedAtOk returns a tuple with the SlaWarnedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetSlaWarnedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SlaWarnedAt) {
		return nil, false
	}
	return o.SlaWarnedAt, true
}

// HasSlaWarnedAt returns a boolean if a field has been set.
func (o *JobRequest) HasSlaWarnedAt() bool {
	if o != nil && !IsNil(o.SlaWarnedAt) {
		return true
	}

	return false
}

// SetSlaWarnedAt gets a reference to the given time.Time and assigns it to the SlaWarnedAt field.
func (o *JobRequest) SetSlaWarnedAt(v time.Time) {
	o.SlaWarnedAt = &v
}

// GetStatusVersion returns the StatusVersion field value if set, zero value otherwise.
func (o *JobRequest) GetStatusVersion() int32 {
	if o == nil || IsNil(o.StatusVersion) {
		var ret int32
		return ret
	}
	return *o.StatusVersion
}

// GetStatusVersionOk returns a tuple with the StatusVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetStatusVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusVersion) {
		return nil, false
	}
	return o.StatusVersion, true
}

// HasStatusVersion returns a boolean if a field has been set.
func (o *JobRequest) HasStatusVersion() bool {
	if o != nil && !IsNil(o.StatusVersion) {
		return true
	}

	return false
}

// SetStatusVersion gets a reference to the given int32 and assigns it to the StatusVersion field.
func (o *JobRequest) SetStatusVersion(v int32) {
	o.StatusVersion = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *JobRequest) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *JobRequest) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *JobRequest) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *JobRequest) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *JobRequest) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *JobRequest) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

// GetWorkflowName returns the WorkflowName field value if set, zero value otherwise.
func (o *JobRequest) GetWorkflowName() string {
	if o == nil || IsNil(o.WorkflowName) {
		var ret string
		return ret
	}
	return *o.WorkflowName
}

// GetWorkflowNameOk returns a tuple with the WorkflowName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequest) GetWorkflowNameOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowName) {
		return nil, false
	}
	return o.WorkflowName, true
}

// HasWorkflowName returns a boolean if a field has been set.
func (o *JobRequest) HasWorkflowName() bool {
	if o != nil && !IsNil(o.WorkflowName) {
		return true
	}

	return false
}

// SetWorkflowName gets a reference to the given string and assigns it to the WorkflowName field.
func (o *JobRequest) SetWorkflowName(v string) {
	o.WorkflowName = &v
}

func (o JobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActionAudit) {
		toSerialize["action_audit"] = o.ActionAudit
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Archive) {
		toSerialize["archive"] = o.Archive
	}
	if !IsNil(o.AssignedVehicle) {
		toSerialize["assigned_vehicle"] = o.AssignedVehicle
	}
	if !IsNil(o.Assignment) {
		toSerialize["assignment"] = o.Assignment
	}
	if !IsNil(o.Attention) {
		toSerialize["attention"] = o.Attention
	}
	if !IsNil(o.BusinessId) {
		toSerialize["business_id"] = o.BusinessId
	}
	if !IsNil(o.CompletedAt) {
		toSerialize["completed_at"] = o.CompletedAt
	}
	if !IsNil(o.CompletedByUserId) {
		toSerialize["completed_by_user_id"] = o.CompletedByUserId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Crew) {
		toSerialize["crew"] = o.Crew
	}
	if !IsNil(o.CurrentStatus) {
		toSerialize["current_status"] = o.CurrentStatus
	}
	if !IsNil(o.Customer) {
		toSerialize["customer"] = o.Customer
	}
	if !IsNil(o.CustomerUrl) {
		toSerialize["customer_url"] = o.CustomerUrl
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.JobTypeId) {
		toSerialize["job_type_id"] = o.JobTypeId
	}
	if !IsNil(o.JobTypeName) {
		toSerialize["job_type_name"] = o.JobTypeName
	}
	if !IsNil(o.NextActions) {
		toSerialize["next_actions"] = o.NextActions
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Quote) {
		toSerialize["quote"] = o.Quote
	}
	if !IsNil(o.Rating) {
		toSerialize["rating"] = o.Rating
	}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.ShortCode) {
		toSerialize["short_code"] = o.ShortCode
	}
	if !IsNil(o.Skills) {
		toSerialize["skills"] = o.Skills
	}
	if !IsNil(o.SlaDeadline) {
		toSerialize["sla_deadline"] = o.SlaDeadline
	}
	if !IsNil(o.SlaEscalatedAt) {
		toSerialize["sla_escalated_at"] = o.SlaEscalatedAt
	}
	if !IsNil(o.SlaWarnedAt) {
		toSerialize["sla_warned_at"] = o.SlaWarnedAt
	}
	if !IsNil(o.StatusVersion) {
		toSerialize["status_version"] = o.StatusVersion
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflow_id"] = o.WorkflowId
	}
	if !IsNil(o.WorkflowName) {
		toSerialize["workflow_name"] = o.WorkflowName
	}
	return toSerialize, nil
}

type NullableJobRequest struct {
	value *JobRequest
	isSet bool
}

func (v NullableJobRequest) Get() *JobRequest {
	return v.value
}

func (v *NullableJobRequest) Set(val *JobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequest(val *JobRequest) *NullableJobRequest {
	return &NullableJobRequest{value: val, isSet: true}
}

func (v NullableJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


