/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
	"time"
)

// checks if the JobRequestTimeSegmentsSlot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestTimeSegmentsSlot{}

// JobRequestTimeSegmentsSlot struct for JobRequestTimeSegmentsSlot
type JobRequestTimeSegmentsSlot struct {
	// Technicians feasible for this slot, engine-ranked best first, each with its score breakdown.
	AvailableWorkers []JobRequestTimeSegmentsWorker `json:"available_workers,omitempty"`
	// True on the first slot of each day — the suggested \"BEST\" pick (UI hint).
	BestTime *bool `json:"best_time,omitempty"`
	// The same arrival window expressed in BUSINESS-local time; its naive datetime is the value to send back on confirm.
	BusinessTime *JobRequestTimeSegmentsBusinessTime `json:"business_time,omitempty"`
	// Window start as an RFC3339 customer-local instant (with UTC offset).
	Datetime *time.Time `json:"datetime,omitempty"`
	// Span end (UTC) of a multi-day visit — render in business/customer timezone. Omitted for single-day slots.
	EndsAt *time.Time `json:"ends_at,omitempty"`
	// MultiDay flags a slot whose visit cannot finish in one day and spans consecutive days. EndsAt + Sessions are then populated (for the best-ranked candidate — the one auto-assign would pick) so the picker can show the customer \"this start runs until <EndsAt>, over N days\" BEFORE they confirm. Single-day slots leave these empty (the slot itself is the visit).
	MultiDay *bool `json:"multi_day,omitempty"`
	// Per-day session plan of a multi-day visit (for the best-ranked candidate). Omitted for single-day slots.
	Sessions []JobRequestSession `json:"sessions,omitempty"`
	// Arrival-window start, HH:MM customer-local.
	Time *string `json:"time,omitempty"`
	// Arrival-window end, HH:MM customer-local (= time + time_slot_step_minutes).
	TimeEnd *string `json:"time_end,omitempty"`
	// Period bucket of the window start: 1=morning, 2=afternoon, 3=evening.
	TimePeriod *int32 `json:"time_period,omitempty"`
	// Localized label for time_period.
	TimePeriodLabel *string `json:"time_period_label,omitempty"`
	// Number of entries in available_workers.
	WorkersCount *int32 `json:"workers_count,omitempty"`
}

// NewJobRequestTimeSegmentsSlot instantiates a new JobRequestTimeSegmentsSlot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestTimeSegmentsSlot() *JobRequestTimeSegmentsSlot {
	this := JobRequestTimeSegmentsSlot{}
	return &this
}

// NewJobRequestTimeSegmentsSlotWithDefaults instantiates a new JobRequestTimeSegmentsSlot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestTimeSegmentsSlotWithDefaults() *JobRequestTimeSegmentsSlot {
	this := JobRequestTimeSegmentsSlot{}
	return &this
}

// GetAvailableWorkers returns the AvailableWorkers field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsSlot) GetAvailableWorkers() []JobRequestTimeSegmentsWorker {
	if o == nil || IsNil(o.AvailableWorkers) {
		var ret []JobRequestTimeSegmentsWorker
		return ret
	}
	return o.AvailableWorkers
}

// GetAvailableWorkersOk returns a tuple with the AvailableWorkers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsSlot) GetAvailableWorkersOk() ([]JobRequestTimeSegmentsWorker, bool) {
	if o == nil || IsNil(o.AvailableWorkers) {
		return nil, false
	}
	return o.AvailableWorkers, true
}

// HasAvailableWorkers returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsSlot) HasAvailableWorkers() bool {
	if o != nil && !IsNil(o.AvailableWorkers) {
		return true
	}

	return false
}

// SetAvailableWorkers gets a reference to the given []JobRequestTimeSegmentsWorker and assigns it to the AvailableWorkers field.
func (o *JobRequestTimeSegmentsSlot) SetAvailableWorkers(v []JobRequestTimeSegmentsWorker) {
	o.AvailableWorkers = v
}

// GetBestTime returns the BestTime field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsSlot) GetBestTime() bool {
	if o == nil || IsNil(o.BestTime) {
		var ret bool
		return ret
	}
	return *o.BestTime
}

// GetBestTimeOk returns a tuple with the BestTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsSlot) GetBestTimeOk() (*bool, bool) {
	if o == nil || IsNil(o.BestTime) {
		return nil, false
	}
	return o.BestTime, true
}

// HasBestTime returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsSlot) HasBestTime() bool {
	if o != nil && !IsNil(o.BestTime) {
		return true
	}

	return false
}

// SetBestTime gets a reference to the given bool and assigns it to the BestTime field.
func (o *JobRequestTimeSegmentsSlot) SetBestTime(v bool) {
	o.BestTime = &v
}

// GetBusinessTime returns the BusinessTime field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsSlot) GetBusinessTime() JobRequestTimeSegmentsBusinessTime {
	if o == nil || IsNil(o.BusinessTime) {
		var ret JobRequestTimeSegmentsBusinessTime
		return ret
	}
	return *o.BusinessTime
}

// GetBusinessTimeOk returns a tuple with the BusinessTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsSlot) GetBusinessTimeOk() (*JobRequestTimeSegmentsBusinessTime, bool) {
	if o == nil || IsNil(o.BusinessTime) {
		return nil, false
	}
	return o.BusinessTime, true
}

// HasBusinessTime returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsSlot) HasBusinessTime() bool {
	if o != nil && !IsNil(o.BusinessTime) {
		return true
	}

	return false
}

// SetBusinessTime gets a reference to the given JobRequestTimeSegmentsBusinessTime and assigns it to the BusinessTime field.
func (o *JobRequestTimeSegmentsSlot) SetBusinessTime(v JobRequestTimeSegmentsBusinessTime) {
	o.BusinessTime = &v
}

// GetDatetime returns the Datetime field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsSlot) GetDatetime() time.Time {
	if o == nil || IsNil(o.Datetime) {
		var ret time.Time
		return ret
	}
	return *o.Datetime
}

// GetDatetimeOk returns a tuple with the Datetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsSlot) GetDatetimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Datetime) {
		return nil, false
	}
	return o.Datetime, true
}

// HasDatetime returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsSlot) HasDatetime() bool {
	if o != nil && !IsNil(o.Datetime) {
		return true
	}

	return false
}

// SetDatetime gets a reference to the given time.Time and assigns it to the Datetime field.
func (o *JobRequestTimeSegmentsSlot) SetDatetime(v time.Time) {
	o.Datetime = &v
}

// GetEndsAt returns the EndsAt field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsSlot) GetEndsAt() time.Time {
	if o == nil || IsNil(o.EndsAt) {
		var ret time.Time
		return ret
	}
	return *o.EndsAt
}

// GetEndsAtOk returns a tuple with the EndsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsSlot) GetEndsAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndsAt) {
		return nil, false
	}
	return o.EndsAt, true
}

// HasEndsAt returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsSlot) HasEndsAt() bool {
	if o != nil && !IsNil(o.EndsAt) {
		return true
	}

	return false
}

// SetEndsAt gets a reference to the given time.Time and assigns it to the EndsAt field.
func (o *JobRequestTimeSegmentsSlot) SetEndsAt(v time.Time) {
	o.EndsAt = &v
}

// GetMultiDay returns the MultiDay field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsSlot) GetMultiDay() bool {
	if o == nil || IsNil(o.MultiDay) {
		var ret bool
		return ret
	}
	return *o.MultiDay
}

// GetMultiDayOk returns a tuple with the MultiDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsSlot) GetMultiDayOk() (*bool, bool) {
	if o == nil || IsNil(o.MultiDay) {
		return nil, false
	}
	return o.MultiDay, true
}

// HasMultiDay returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsSlot) HasMultiDay() bool {
	if o != nil && !IsNil(o.MultiDay) {
		return true
	}

	return false
}

// SetMultiDay gets a reference to the given bool and assigns it to the MultiDay field.
func (o *JobRequestTimeSegmentsSlot) SetMultiDay(v bool) {
	o.MultiDay = &v
}

// GetSessions returns the Sessions field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsSlot) GetSessions() []JobRequestSession {
	if o == nil || IsNil(o.Sessions) {
		var ret []JobRequestSession
		return ret
	}
	return o.Sessions
}

// GetSessionsOk returns a tuple with the Sessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsSlot) GetSessionsOk() ([]JobRequestSession, bool) {
	if o == nil || IsNil(o.Sessions) {
		return nil, false
	}
	return o.Sessions, true
}

// HasSessions returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsSlot) HasSessions() bool {
	if o != nil && !IsNil(o.Sessions) {
		return true
	}

	return false
}

// SetSessions gets a reference to the given []JobRequestSession and assigns it to the Sessions field.
func (o *JobRequestTimeSegmentsSlot) SetSessions(v []JobRequestSession) {
	o.Sessions = v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsSlot) GetTime() string {
	if o == nil || IsNil(o.Time) {
		var ret string
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsSlot) GetTimeOk() (*string, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsSlot) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given string and assigns it to the Time field.
func (o *JobRequestTimeSegmentsSlot) SetTime(v string) {
	o.Time = &v
}

// GetTimeEnd returns the TimeEnd field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsSlot) GetTimeEnd() string {
	if o == nil || IsNil(o.TimeEnd) {
		var ret string
		return ret
	}
	return *o.TimeEnd
}

// GetTimeEndOk returns a tuple with the TimeEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsSlot) GetTimeEndOk() (*string, bool) {
	if o == nil || IsNil(o.TimeEnd) {
		return nil, false
	}
	return o.TimeEnd, true
}

// HasTimeEnd returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsSlot) HasTimeEnd() bool {
	if o != nil && !IsNil(o.TimeEnd) {
		return true
	}

	return false
}

// SetTimeEnd gets a reference to the given string and assigns it to the TimeEnd field.
func (o *JobRequestTimeSegmentsSlot) SetTimeEnd(v string) {
	o.TimeEnd = &v
}

// GetTimePeriod returns the TimePeriod field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsSlot) GetTimePeriod() int32 {
	if o == nil || IsNil(o.TimePeriod) {
		var ret int32
		return ret
	}
	return *o.TimePeriod
}

// GetTimePeriodOk returns a tuple with the TimePeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsSlot) GetTimePeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.TimePeriod) {
		return nil, false
	}
	return o.TimePeriod, true
}

// HasTimePeriod returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsSlot) HasTimePeriod() bool {
	if o != nil && !IsNil(o.TimePeriod) {
		return true
	}

	return false
}

// SetTimePeriod gets a reference to the given int32 and assigns it to the TimePeriod field.
func (o *JobRequestTimeSegmentsSlot) SetTimePeriod(v int32) {
	o.TimePeriod = &v
}

// GetTimePeriodLabel returns the TimePeriodLabel field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsSlot) GetTimePeriodLabel() string {
	if o == nil || IsNil(o.TimePeriodLabel) {
		var ret string
		return ret
	}
	return *o.TimePeriodLabel
}

// GetTimePeriodLabelOk returns a tuple with the TimePeriodLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsSlot) GetTimePeriodLabelOk() (*string, bool) {
	if o == nil || IsNil(o.TimePeriodLabel) {
		return nil, false
	}
	return o.TimePeriodLabel, true
}

// HasTimePeriodLabel returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsSlot) HasTimePeriodLabel() bool {
	if o != nil && !IsNil(o.TimePeriodLabel) {
		return true
	}

	return false
}

// SetTimePeriodLabel gets a reference to the given string and assigns it to the TimePeriodLabel field.
func (o *JobRequestTimeSegmentsSlot) SetTimePeriodLabel(v string) {
	o.TimePeriodLabel = &v
}

// GetWorkersCount returns the WorkersCount field value if set, zero value otherwise.
func (o *JobRequestTimeSegmentsSlot) GetWorkersCount() int32 {
	if o == nil || IsNil(o.WorkersCount) {
		var ret int32
		return ret
	}
	return *o.WorkersCount
}

// GetWorkersCountOk returns a tuple with the WorkersCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeSegmentsSlot) GetWorkersCountOk() (*int32, bool) {
	if o == nil || IsNil(o.WorkersCount) {
		return nil, false
	}
	return o.WorkersCount, true
}

// HasWorkersCount returns a boolean if a field has been set.
func (o *JobRequestTimeSegmentsSlot) HasWorkersCount() bool {
	if o != nil && !IsNil(o.WorkersCount) {
		return true
	}

	return false
}

// SetWorkersCount gets a reference to the given int32 and assigns it to the WorkersCount field.
func (o *JobRequestTimeSegmentsSlot) SetWorkersCount(v int32) {
	o.WorkersCount = &v
}

func (o JobRequestTimeSegmentsSlot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestTimeSegmentsSlot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvailableWorkers) {
		toSerialize["available_workers"] = o.AvailableWorkers
	}
	if !IsNil(o.BestTime) {
		toSerialize["best_time"] = o.BestTime
	}
	if !IsNil(o.BusinessTime) {
		toSerialize["business_time"] = o.BusinessTime
	}
	if !IsNil(o.Datetime) {
		toSerialize["datetime"] = o.Datetime
	}
	if !IsNil(o.EndsAt) {
		toSerialize["ends_at"] = o.EndsAt
	}
	if !IsNil(o.MultiDay) {
		toSerialize["multi_day"] = o.MultiDay
	}
	if !IsNil(o.Sessions) {
		toSerialize["sessions"] = o.Sessions
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.TimeEnd) {
		toSerialize["time_end"] = o.TimeEnd
	}
	if !IsNil(o.TimePeriod) {
		toSerialize["time_period"] = o.TimePeriod
	}
	if !IsNil(o.TimePeriodLabel) {
		toSerialize["time_period_label"] = o.TimePeriodLabel
	}
	if !IsNil(o.WorkersCount) {
		toSerialize["workers_count"] = o.WorkersCount
	}
	return toSerialize, nil
}

type NullableJobRequestTimeSegmentsSlot struct {
	value *JobRequestTimeSegmentsSlot
	isSet bool
}

func (v NullableJobRequestTimeSegmentsSlot) Get() *JobRequestTimeSegmentsSlot {
	return v.value
}

func (v *NullableJobRequestTimeSegmentsSlot) Set(val *JobRequestTimeSegmentsSlot) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestTimeSegmentsSlot) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestTimeSegmentsSlot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestTimeSegmentsSlot(val *JobRequestTimeSegmentsSlot) *NullableJobRequestTimeSegmentsSlot {
	return &NullableJobRequestTimeSegmentsSlot{value: val, isSet: true}
}

func (v NullableJobRequestTimeSegmentsSlot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestTimeSegmentsSlot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


