/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the JobRequestTimeline type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestTimeline{}

// JobRequestTimeline struct for JobRequestTimeline
type JobRequestTimeline struct {
	// Status key the job is currently in.
	CurrentStatusKey *string `json:"current_status_key,omitempty"`
	// Status rows in workflow order (booking → … → completed).
	Events []JobRequestTimelineEvent `json:"events,omitempty"`
	// Optimistic-lock version of the job (read-only here; timeline does not bump it).
	StatusVersion *int32 `json:"status_version,omitempty"`
	// UUID of the workflow snapshot driving this job.
	WorkflowId *string `json:"workflow_id,omitempty"`
	// Workflow display name.
	WorkflowName *string `json:"workflow_name,omitempty"`
}

// NewJobRequestTimeline instantiates a new JobRequestTimeline object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestTimeline() *JobRequestTimeline {
	this := JobRequestTimeline{}
	return &this
}

// NewJobRequestTimelineWithDefaults instantiates a new JobRequestTimeline object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestTimelineWithDefaults() *JobRequestTimeline {
	this := JobRequestTimeline{}
	return &this
}

// GetCurrentStatusKey returns the CurrentStatusKey field value if set, zero value otherwise.
func (o *JobRequestTimeline) GetCurrentStatusKey() string {
	if o == nil || IsNil(o.CurrentStatusKey) {
		var ret string
		return ret
	}
	return *o.CurrentStatusKey
}

// GetCurrentStatusKeyOk returns a tuple with the CurrentStatusKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeline) GetCurrentStatusKeyOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentStatusKey) {
		return nil, false
	}
	return o.CurrentStatusKey, true
}

// HasCurrentStatusKey returns a boolean if a field has been set.
func (o *JobRequestTimeline) HasCurrentStatusKey() bool {
	if o != nil && !IsNil(o.CurrentStatusKey) {
		return true
	}

	return false
}

// SetCurrentStatusKey gets a reference to the given string and assigns it to the CurrentStatusKey field.
func (o *JobRequestTimeline) SetCurrentStatusKey(v string) {
	o.CurrentStatusKey = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *JobRequestTimeline) GetEvents() []JobRequestTimelineEvent {
	if o == nil || IsNil(o.Events) {
		var ret []JobRequestTimelineEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeline) GetEventsOk() ([]JobRequestTimelineEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *JobRequestTimeline) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []JobRequestTimelineEvent and assigns it to the Events field.
func (o *JobRequestTimeline) SetEvents(v []JobRequestTimelineEvent) {
	o.Events = v
}

// GetStatusVersion returns the StatusVersion field value if set, zero value otherwise.
func (o *JobRequestTimeline) GetStatusVersion() int32 {
	if o == nil || IsNil(o.StatusVersion) {
		var ret int32
		return ret
	}
	return *o.StatusVersion
}

// GetStatusVersionOk returns a tuple with the StatusVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeline) GetStatusVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusVersion) {
		return nil, false
	}
	return o.StatusVersion, true
}

// HasStatusVersion returns a boolean if a field has been set.
func (o *JobRequestTimeline) HasStatusVersion() bool {
	if o != nil && !IsNil(o.StatusVersion) {
		return true
	}

	return false
}

// SetStatusVersion gets a reference to the given int32 and assigns it to the StatusVersion field.
func (o *JobRequestTimeline) SetStatusVersion(v int32) {
	o.StatusVersion = &v
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *JobRequestTimeline) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeline) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *JobRequestTimeline) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *JobRequestTimeline) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

// GetWorkflowName returns the WorkflowName field value if set, zero value otherwise.
func (o *JobRequestTimeline) GetWorkflowName() string {
	if o == nil || IsNil(o.WorkflowName) {
		var ret string
		return ret
	}
	return *o.WorkflowName
}

// GetWorkflowNameOk returns a tuple with the WorkflowName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestTimeline) GetWorkflowNameOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowName) {
		return nil, false
	}
	return o.WorkflowName, true
}

// HasWorkflowName returns a boolean if a field has been set.
func (o *JobRequestTimeline) HasWorkflowName() bool {
	if o != nil && !IsNil(o.WorkflowName) {
		return true
	}

	return false
}

// SetWorkflowName gets a reference to the given string and assigns it to the WorkflowName field.
func (o *JobRequestTimeline) SetWorkflowName(v string) {
	o.WorkflowName = &v
}

func (o JobRequestTimeline) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestTimeline) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrentStatusKey) {
		toSerialize["current_status_key"] = o.CurrentStatusKey
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.StatusVersion) {
		toSerialize["status_version"] = o.StatusVersion
	}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflow_id"] = o.WorkflowId
	}
	if !IsNil(o.WorkflowName) {
		toSerialize["workflow_name"] = o.WorkflowName
	}
	return toSerialize, nil
}

type NullableJobRequestTimeline struct {
	value *JobRequestTimeline
	isSet bool
}

func (v NullableJobRequestTimeline) Get() *JobRequestTimeline {
	return v.value
}

func (v *NullableJobRequestTimeline) Set(val *JobRequestTimeline) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestTimeline) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestTimeline) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestTimeline(val *JobRequestTimeline) *NullableJobRequestTimeline {
	return &NullableJobRequestTimeline{value: val, isSet: true}
}

func (v NullableJobRequestTimeline) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestTimeline) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


