/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the JobRequestConfirmRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestConfirmRequest{}

// JobRequestConfirmRequest struct for JobRequestConfirmRequest
type JobRequestConfirmRequest struct {
	// ArrivalWindowMinutes = width (phút) của arrival-window ô khách bấm ở slot-picker (chính là time_slot_step_minutes, mặc định 30). Persist để post-confirm detail render lại đúng window. Optional; bounds ([5, 240], khớp slot-picker step) validate ở usecase — single authority, một error code (JOB_REQUEST_INVALID_INPUT).
	ArrivalWindowMinutes *int32 `json:"arrival_window_minutes,omitempty"`
	// Chosen start time — business-local naive datetime, no offset (the business_time.datetime value from the time-segments picker). The server converts to UTC using the job's business timezone.
	ScheduledAt *string `json:"scheduled_at,omitempty"`
	// Optimistic-lock fence: the status_version from your last read. Omitted/0 = fence on the row's current version (no race protection).
	StatusVersion *int32 `json:"status_version,omitempty"`
	// TechnicianID (BUSINESS confirm only — ignored on the customer surface): force-assign the job to this technician instead of the ranked auto-pick. Ranking is bypassed; feasibility (hours/time-off/geo/skills), the TierLead rule and the double-booking guard still apply — an infeasible forced tech rejects the confirm (P0 gets the displacement hint).
	TechnicianId *string `json:"technician_id,omitempty"`
}

// NewJobRequestConfirmRequest instantiates a new JobRequestConfirmRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestConfirmRequest() *JobRequestConfirmRequest {
	this := JobRequestConfirmRequest{}
	return &this
}

// NewJobRequestConfirmRequestWithDefaults instantiates a new JobRequestConfirmRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestConfirmRequestWithDefaults() *JobRequestConfirmRequest {
	this := JobRequestConfirmRequest{}
	return &this
}

// GetArrivalWindowMinutes returns the ArrivalWindowMinutes field value if set, zero value otherwise.
func (o *JobRequestConfirmRequest) GetArrivalWindowMinutes() int32 {
	if o == nil || IsNil(o.ArrivalWindowMinutes) {
		var ret int32
		return ret
	}
	return *o.ArrivalWindowMinutes
}

// GetArrivalWindowMinutesOk returns a tuple with the ArrivalWindowMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestConfirmRequest) GetArrivalWindowMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.ArrivalWindowMinutes) {
		return nil, false
	}
	return o.ArrivalWindowMinutes, true
}

// HasArrivalWindowMinutes returns a boolean if a field has been set.
func (o *JobRequestConfirmRequest) HasArrivalWindowMinutes() bool {
	if o != nil && !IsNil(o.ArrivalWindowMinutes) {
		return true
	}

	return false
}

// SetArrivalWindowMinutes gets a reference to the given int32 and assigns it to the ArrivalWindowMinutes field.
func (o *JobRequestConfirmRequest) SetArrivalWindowMinutes(v int32) {
	o.ArrivalWindowMinutes = &v
}

// GetScheduledAt returns the ScheduledAt field value if set, zero value otherwise.
func (o *JobRequestConfirmRequest) GetScheduledAt() string {
	if o == nil || IsNil(o.ScheduledAt) {
		var ret string
		return ret
	}
	return *o.ScheduledAt
}

// GetScheduledAtOk returns a tuple with the ScheduledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestConfirmRequest) GetScheduledAtOk() (*string, bool) {
	if o == nil || IsNil(o.ScheduledAt) {
		return nil, false
	}
	return o.ScheduledAt, true
}

// HasScheduledAt returns a boolean if a field has been set.
func (o *JobRequestConfirmRequest) HasScheduledAt() bool {
	if o != nil && !IsNil(o.ScheduledAt) {
		return true
	}

	return false
}

// SetScheduledAt gets a reference to the given string and assigns it to the ScheduledAt field.
func (o *JobRequestConfirmRequest) SetScheduledAt(v string) {
	o.ScheduledAt = &v
}

// GetStatusVersion returns the StatusVersion field value if set, zero value otherwise.
func (o *JobRequestConfirmRequest) GetStatusVersion() int32 {
	if o == nil || IsNil(o.StatusVersion) {
		var ret int32
		return ret
	}
	return *o.StatusVersion
}

// GetStatusVersionOk returns a tuple with the StatusVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestConfirmRequest) GetStatusVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusVersion) {
		return nil, false
	}
	return o.StatusVersion, true
}

// HasStatusVersion returns a boolean if a field has been set.
func (o *JobRequestConfirmRequest) HasStatusVersion() bool {
	if o != nil && !IsNil(o.StatusVersion) {
		return true
	}

	return false
}

// SetStatusVersion gets a reference to the given int32 and assigns it to the StatusVersion field.
func (o *JobRequestConfirmRequest) SetStatusVersion(v int32) {
	o.StatusVersion = &v
}

// GetTechnicianId returns the TechnicianId field value if set, zero value otherwise.
func (o *JobRequestConfirmRequest) GetTechnicianId() string {
	if o == nil || IsNil(o.TechnicianId) {
		var ret string
		return ret
	}
	return *o.TechnicianId
}

// GetTechnicianIdOk returns a tuple with the TechnicianId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestConfirmRequest) GetTechnicianIdOk() (*string, bool) {
	if o == nil || IsNil(o.TechnicianId) {
		return nil, false
	}
	return o.TechnicianId, true
}

// HasTechnicianId returns a boolean if a field has been set.
func (o *JobRequestConfirmRequest) HasTechnicianId() bool {
	if o != nil && !IsNil(o.TechnicianId) {
		return true
	}

	return false
}

// SetTechnicianId gets a reference to the given string and assigns it to the TechnicianId field.
func (o *JobRequestConfirmRequest) SetTechnicianId(v string) {
	o.TechnicianId = &v
}

func (o JobRequestConfirmRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestConfirmRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ArrivalWindowMinutes) {
		toSerialize["arrival_window_minutes"] = o.ArrivalWindowMinutes
	}
	if !IsNil(o.ScheduledAt) {
		toSerialize["scheduled_at"] = o.ScheduledAt
	}
	if !IsNil(o.StatusVersion) {
		toSerialize["status_version"] = o.StatusVersion
	}
	if !IsNil(o.TechnicianId) {
		toSerialize["technician_id"] = o.TechnicianId
	}
	return toSerialize, nil
}

type NullableJobRequestConfirmRequest struct {
	value *JobRequestConfirmRequest
	isSet bool
}

func (v NullableJobRequestConfirmRequest) Get() *JobRequestConfirmRequest {
	return v.value
}

func (v *NullableJobRequestConfirmRequest) Set(val *JobRequestConfirmRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestConfirmRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestConfirmRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestConfirmRequest(val *JobRequestConfirmRequest) *NullableJobRequestConfirmRequest {
	return &NullableJobRequestConfirmRequest{value: val, isSet: true}
}

func (v NullableJobRequestConfirmRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestConfirmRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


