/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
	"time"
)

// checks if the JobRequestSchedule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestSchedule{}

// JobRequestSchedule struct for JobRequestSchedule
type JobRequestSchedule struct {
	// ArrivalWindow is the [start, start+window_minutes] arrival window the customer sees after confirming. start/end UTC — render in business/customer timezone. Omitted until confirmed.
	ArrivalWindow *JobRequestArrivalWindow `json:"arrival_window,omitempty"`
	// IANA timezone of the business. Omitted if unknown.
	BusinessTimezone *string `json:"business_timezone,omitempty"`
	// IANA timezone of the customer. Omitted if unknown.
	CustomerTimezone *string `json:"customer_timezone,omitempty"`
	// EndsAt is the job's span END (last session end, UTC). For a multi-day job it falls on a LATER calendar day than scheduled_at — render \"starts D1 → ends Dn\". Nil when no session plan exists.
	EndsAt *time.Time `json:"ends_at,omitempty"`
	// Requested date(s)/period(s) captured at booking. Omitted once confirmed/scheduled. Use regional.JobDate directly (not the jobrequest.JobDate alias) so swag emits a single canonical `JobDate` schema instead of an aliased duplicate.
	JobDates []JobDate `json:"job_dates,omitempty"`
	// Confirmed start time (UTC); null until the customer confirms. Render in business/customer timezone.
	ScheduledAt *time.Time `json:"scheduled_at,omitempty"`
	// Total scheduled duration in minutes (job + mobilization + demobilization); null until quoted.
	ScheduledDurationMinutes *int32 `json:"scheduled_duration_minutes,omitempty"`
	// Sessions is the per-day on-site breakdown (ordered): one for single-day, several for multi-day.
	Sessions []JobRequestSession `json:"sessions,omitempty"`
}

// NewJobRequestSchedule instantiates a new JobRequestSchedule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestSchedule() *JobRequestSchedule {
	this := JobRequestSchedule{}
	return &this
}

// NewJobRequestScheduleWithDefaults instantiates a new JobRequestSchedule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestScheduleWithDefaults() *JobRequestSchedule {
	this := JobRequestSchedule{}
	return &this
}

// GetArrivalWindow returns the ArrivalWindow field value if set, zero value otherwise.
func (o *JobRequestSchedule) GetArrivalWindow() JobRequestArrivalWindow {
	if o == nil || IsNil(o.ArrivalWindow) {
		var ret JobRequestArrivalWindow
		return ret
	}
	return *o.ArrivalWindow
}

// GetArrivalWindowOk returns a tuple with the ArrivalWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSchedule) GetArrivalWindowOk() (*JobRequestArrivalWindow, bool) {
	if o == nil || IsNil(o.ArrivalWindow) {
		return nil, false
	}
	return o.ArrivalWindow, true
}

// HasArrivalWindow returns a boolean if a field has been set.
func (o *JobRequestSchedule) HasArrivalWindow() bool {
	if o != nil && !IsNil(o.ArrivalWindow) {
		return true
	}

	return false
}

// SetArrivalWindow gets a reference to the given JobRequestArrivalWindow and assigns it to the ArrivalWindow field.
func (o *JobRequestSchedule) SetArrivalWindow(v JobRequestArrivalWindow) {
	o.ArrivalWindow = &v
}

// GetBusinessTimezone returns the BusinessTimezone field value if set, zero value otherwise.
func (o *JobRequestSchedule) GetBusinessTimezone() string {
	if o == nil || IsNil(o.BusinessTimezone) {
		var ret string
		return ret
	}
	return *o.BusinessTimezone
}

// GetBusinessTimezoneOk returns a tuple with the BusinessTimezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSchedule) GetBusinessTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessTimezone) {
		return nil, false
	}
	return o.BusinessTimezone, true
}

// HasBusinessTimezone returns a boolean if a field has been set.
func (o *JobRequestSchedule) HasBusinessTimezone() bool {
	if o != nil && !IsNil(o.BusinessTimezone) {
		return true
	}

	return false
}

// SetBusinessTimezone gets a reference to the given string and assigns it to the BusinessTimezone field.
func (o *JobRequestSchedule) SetBusinessTimezone(v string) {
	o.BusinessTimezone = &v
}

// GetCustomerTimezone returns the CustomerTimezone field value if set, zero value otherwise.
func (o *JobRequestSchedule) GetCustomerTimezone() string {
	if o == nil || IsNil(o.CustomerTimezone) {
		var ret string
		return ret
	}
	return *o.CustomerTimezone
}

// GetCustomerTimezoneOk returns a tuple with the CustomerTimezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSchedule) GetCustomerTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerTimezone) {
		return nil, false
	}
	return o.CustomerTimezone, true
}

// HasCustomerTimezone returns a boolean if a field has been set.
func (o *JobRequestSchedule) HasCustomerTimezone() bool {
	if o != nil && !IsNil(o.CustomerTimezone) {
		return true
	}

	return false
}

// SetCustomerTimezone gets a reference to the given string and assigns it to the CustomerTimezone field.
func (o *JobRequestSchedule) SetCustomerTimezone(v string) {
	o.CustomerTimezone = &v
}

// GetEndsAt returns the EndsAt field value if set, zero value otherwise.
func (o *JobRequestSchedule) GetEndsAt() time.Time {
	if o == nil || IsNil(o.EndsAt) {
		var ret time.Time
		return ret
	}
	return *o.EndsAt
}

// GetEndsAtOk returns a tuple with the EndsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSchedule) GetEndsAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndsAt) {
		return nil, false
	}
	return o.EndsAt, true
}

// HasEndsAt returns a boolean if a field has been set.
func (o *JobRequestSchedule) HasEndsAt() bool {
	if o != nil && !IsNil(o.EndsAt) {
		return true
	}

	return false
}

// SetEndsAt gets a reference to the given time.Time and assigns it to the EndsAt field.
func (o *JobRequestSchedule) SetEndsAt(v time.Time) {
	o.EndsAt = &v
}

// GetJobDates returns the JobDates field value if set, zero value otherwise.
func (o *JobRequestSchedule) GetJobDates() []JobDate {
	if o == nil || IsNil(o.JobDates) {
		var ret []JobDate
		return ret
	}
	return o.JobDates
}

// GetJobDatesOk returns a tuple with the JobDates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSchedule) GetJobDatesOk() ([]JobDate, bool) {
	if o == nil || IsNil(o.JobDates) {
		return nil, false
	}
	return o.JobDates, true
}

// HasJobDates returns a boolean if a field has been set.
func (o *JobRequestSchedule) HasJobDates() bool {
	if o != nil && !IsNil(o.JobDates) {
		return true
	}

	return false
}

// SetJobDates gets a reference to the given []JobDate and assigns it to the JobDates field.
func (o *JobRequestSchedule) SetJobDates(v []JobDate) {
	o.JobDates = v
}

// GetScheduledAt returns the ScheduledAt field value if set, zero value otherwise.
func (o *JobRequestSchedule) GetScheduledAt() time.Time {
	if o == nil || IsNil(o.ScheduledAt) {
		var ret time.Time
		return ret
	}
	return *o.ScheduledAt
}

// GetScheduledAtOk returns a tuple with the ScheduledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSchedule) GetScheduledAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ScheduledAt) {
		return nil, false
	}
	return o.ScheduledAt, true
}

// HasScheduledAt returns a boolean if a field has been set.
func (o *JobRequestSchedule) HasScheduledAt() bool {
	if o != nil && !IsNil(o.ScheduledAt) {
		return true
	}

	return false
}

// SetScheduledAt gets a reference to the given time.Time and assigns it to the ScheduledAt field.
func (o *JobRequestSchedule) SetScheduledAt(v time.Time) {
	o.ScheduledAt = &v
}

// GetScheduledDurationMinutes returns the ScheduledDurationMinutes field value if set, zero value otherwise.
func (o *JobRequestSchedule) GetScheduledDurationMinutes() int32 {
	if o == nil || IsNil(o.ScheduledDurationMinutes) {
		var ret int32
		return ret
	}
	return *o.ScheduledDurationMinutes
}

// GetScheduledDurationMinutesOk returns a tuple with the ScheduledDurationMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSchedule) GetScheduledDurationMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.ScheduledDurationMinutes) {
		return nil, false
	}
	return o.ScheduledDurationMinutes, true
}

// HasScheduledDurationMinutes returns a boolean if a field has been set.
func (o *JobRequestSchedule) HasScheduledDurationMinutes() bool {
	if o != nil && !IsNil(o.ScheduledDurationMinutes) {
		return true
	}

	return false
}

// SetScheduledDurationMinutes gets a reference to the given int32 and assigns it to the ScheduledDurationMinutes field.
func (o *JobRequestSchedule) SetScheduledDurationMinutes(v int32) {
	o.ScheduledDurationMinutes = &v
}

// GetSessions returns the Sessions field value if set, zero value otherwise.
func (o *JobRequestSchedule) GetSessions() []JobRequestSession {
	if o == nil || IsNil(o.Sessions) {
		var ret []JobRequestSession
		return ret
	}
	return o.Sessions
}

// GetSessionsOk returns a tuple with the Sessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestSchedule) GetSessionsOk() ([]JobRequestSession, bool) {
	if o == nil || IsNil(o.Sessions) {
		return nil, false
	}
	return o.Sessions, true
}

// HasSessions returns a boolean if a field has been set.
func (o *JobRequestSchedule) HasSessions() bool {
	if o != nil && !IsNil(o.Sessions) {
		return true
	}

	return false
}

// SetSessions gets a reference to the given []JobRequestSession and assigns it to the Sessions field.
func (o *JobRequestSchedule) SetSessions(v []JobRequestSession) {
	o.Sessions = v
}

func (o JobRequestSchedule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestSchedule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ArrivalWindow) {
		toSerialize["arrival_window"] = o.ArrivalWindow
	}
	if !IsNil(o.BusinessTimezone) {
		toSerialize["business_timezone"] = o.BusinessTimezone
	}
	if !IsNil(o.CustomerTimezone) {
		toSerialize["customer_timezone"] = o.CustomerTimezone
	}
	if !IsNil(o.EndsAt) {
		toSerialize["ends_at"] = o.EndsAt
	}
	if !IsNil(o.JobDates) {
		toSerialize["job_dates"] = o.JobDates
	}
	if !IsNil(o.ScheduledAt) {
		toSerialize["scheduled_at"] = o.ScheduledAt
	}
	if !IsNil(o.ScheduledDurationMinutes) {
		toSerialize["scheduled_duration_minutes"] = o.ScheduledDurationMinutes
	}
	if !IsNil(o.Sessions) {
		toSerialize["sessions"] = o.Sessions
	}
	return toSerialize, nil
}

type NullableJobRequestSchedule struct {
	value *JobRequestSchedule
	isSet bool
}

func (v NullableJobRequestSchedule) Get() *JobRequestSchedule {
	return v.value
}

func (v *NullableJobRequestSchedule) Set(val *JobRequestSchedule) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestSchedule) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestSchedule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestSchedule(val *JobRequestSchedule) *NullableJobRequestSchedule {
	return &NullableJobRequestSchedule{value: val, isSet: true}
}

func (v NullableJobRequestSchedule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestSchedule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


