/*
CrispHive Developer API

Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the SkillCategoryList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkillCategoryList{}

// SkillCategoryList struct for SkillCategoryList
type SkillCategoryList struct {
	Categories []SkillCategory `json:"categories,omitempty"`
	Meta *Pagination `json:"meta,omitempty"`
}

// NewSkillCategoryList instantiates a new SkillCategoryList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkillCategoryList() *SkillCategoryList {
	this := SkillCategoryList{}
	return &this
}

// NewSkillCategoryListWithDefaults instantiates a new SkillCategoryList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkillCategoryListWithDefaults() *SkillCategoryList {
	this := SkillCategoryList{}
	return &this
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *SkillCategoryList) GetCategories() []SkillCategory {
	if o == nil || IsNil(o.Categories) {
		var ret []SkillCategory
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkillCategoryList) GetCategoriesOk() ([]SkillCategory, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *SkillCategoryList) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []SkillCategory and assigns it to the Categories field.
func (o *SkillCategoryList) SetCategories(v []SkillCategory) {
	o.Categories = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SkillCategoryList) GetMeta() Pagination {
	if o == nil || IsNil(o.Meta) {
		var ret Pagination
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkillCategoryList) GetMetaOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SkillCategoryList) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given Pagination and assigns it to the Meta field.
func (o *SkillCategoryList) SetMeta(v Pagination) {
	o.Meta = &v
}

func (o SkillCategoryList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkillCategoryList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableSkillCategoryList struct {
	value *SkillCategoryList
	isSet bool
}

func (v NullableSkillCategoryList) Get() *SkillCategoryList {
	return v.value
}

func (v *NullableSkillCategoryList) Set(val *SkillCategoryList) {
	v.value = val
	v.isSet = true
}

func (v NullableSkillCategoryList) IsSet() bool {
	return v.isSet
}

func (v *NullableSkillCategoryList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkillCategoryList(val *SkillCategoryList) *NullableSkillCategoryList {
	return &NullableSkillCategoryList{value: val, isSet: true}
}

func (v NullableSkillCategoryList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkillCategoryList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


