/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the JobRequestBusinessTimeRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestBusinessTimeRange{}

// JobRequestBusinessTimeRange struct for JobRequestBusinessTimeRange
type JobRequestBusinessTimeRange struct {
	// Calendar day (YYYY-MM-DD), business-local.
	Date *string `json:"date,omitempty"`
	// Range end as minutes since midnight (0–1440), business-local.
	EndMinute *int32 `json:"end_minute,omitempty"`
	// Time-of-day period this range belongs to.
	Period *string `json:"period,omitempty"`
	// Range start as minutes since midnight (0–1440), business-local.
	StartMinute *int32 `json:"start_minute,omitempty"`
}

// NewJobRequestBusinessTimeRange instantiates a new JobRequestBusinessTimeRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestBusinessTimeRange() *JobRequestBusinessTimeRange {
	this := JobRequestBusinessTimeRange{}
	return &this
}

// NewJobRequestBusinessTimeRangeWithDefaults instantiates a new JobRequestBusinessTimeRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestBusinessTimeRangeWithDefaults() *JobRequestBusinessTimeRange {
	this := JobRequestBusinessTimeRange{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *JobRequestBusinessTimeRange) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestBusinessTimeRange) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *JobRequestBusinessTimeRange) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *JobRequestBusinessTimeRange) SetDate(v string) {
	o.Date = &v
}

// GetEndMinute returns the EndMinute field value if set, zero value otherwise.
func (o *JobRequestBusinessTimeRange) GetEndMinute() int32 {
	if o == nil || IsNil(o.EndMinute) {
		var ret int32
		return ret
	}
	return *o.EndMinute
}

// GetEndMinuteOk returns a tuple with the EndMinute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestBusinessTimeRange) GetEndMinuteOk() (*int32, bool) {
	if o == nil || IsNil(o.EndMinute) {
		return nil, false
	}
	return o.EndMinute, true
}

// HasEndMinute returns a boolean if a field has been set.
func (o *JobRequestBusinessTimeRange) HasEndMinute() bool {
	if o != nil && !IsNil(o.EndMinute) {
		return true
	}

	return false
}

// SetEndMinute gets a reference to the given int32 and assigns it to the EndMinute field.
func (o *JobRequestBusinessTimeRange) SetEndMinute(v int32) {
	o.EndMinute = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *JobRequestBusinessTimeRange) GetPeriod() string {
	if o == nil || IsNil(o.Period) {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestBusinessTimeRange) GetPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *JobRequestBusinessTimeRange) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *JobRequestBusinessTimeRange) SetPeriod(v string) {
	o.Period = &v
}

// GetStartMinute returns the StartMinute field value if set, zero value otherwise.
func (o *JobRequestBusinessTimeRange) GetStartMinute() int32 {
	if o == nil || IsNil(o.StartMinute) {
		var ret int32
		return ret
	}
	return *o.StartMinute
}

// GetStartMinuteOk returns a tuple with the StartMinute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestBusinessTimeRange) GetStartMinuteOk() (*int32, bool) {
	if o == nil || IsNil(o.StartMinute) {
		return nil, false
	}
	return o.StartMinute, true
}

// HasStartMinute returns a boolean if a field has been set.
func (o *JobRequestBusinessTimeRange) HasStartMinute() bool {
	if o != nil && !IsNil(o.StartMinute) {
		return true
	}

	return false
}

// SetStartMinute gets a reference to the given int32 and assigns it to the StartMinute field.
func (o *JobRequestBusinessTimeRange) SetStartMinute(v int32) {
	o.StartMinute = &v
}

func (o JobRequestBusinessTimeRange) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestBusinessTimeRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.EndMinute) {
		toSerialize["end_minute"] = o.EndMinute
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.StartMinute) {
		toSerialize["start_minute"] = o.StartMinute
	}
	return toSerialize, nil
}

type NullableJobRequestBusinessTimeRange struct {
	value *JobRequestBusinessTimeRange
	isSet bool
}

func (v NullableJobRequestBusinessTimeRange) Get() *JobRequestBusinessTimeRange {
	return v.value
}

func (v *NullableJobRequestBusinessTimeRange) Set(val *JobRequestBusinessTimeRange) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestBusinessTimeRange) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestBusinessTimeRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestBusinessTimeRange(val *JobRequestBusinessTimeRange) *NullableJobRequestBusinessTimeRange {
	return &NullableJobRequestBusinessTimeRange{value: val, isSet: true}
}

func (v NullableJobRequestBusinessTimeRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestBusinessTimeRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


