/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the JobDate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobDate{}

// JobDate struct for JobDate
type JobDate struct {
	// Requested calendar day (YYYY-MM-DD), customer-local.
	Date *string `json:"date,omitempty"`
	// Time-of-day periods picked on this date.
	Periods []JobDatePeriodEntry `json:"periods,omitempty"`
}

// NewJobDate instantiates a new JobDate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobDate() *JobDate {
	this := JobDate{}
	return &this
}

// NewJobDateWithDefaults instantiates a new JobDate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobDateWithDefaults() *JobDate {
	this := JobDate{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *JobDate) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobDate) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *JobDate) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *JobDate) SetDate(v string) {
	o.Date = &v
}

// GetPeriods returns the Periods field value if set, zero value otherwise.
func (o *JobDate) GetPeriods() []JobDatePeriodEntry {
	if o == nil || IsNil(o.Periods) {
		var ret []JobDatePeriodEntry
		return ret
	}
	return o.Periods
}

// GetPeriodsOk returns a tuple with the Periods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobDate) GetPeriodsOk() ([]JobDatePeriodEntry, bool) {
	if o == nil || IsNil(o.Periods) {
		return nil, false
	}
	return o.Periods, true
}

// HasPeriods returns a boolean if a field has been set.
func (o *JobDate) HasPeriods() bool {
	if o != nil && !IsNil(o.Periods) {
		return true
	}

	return false
}

// SetPeriods gets a reference to the given []JobDatePeriodEntry and assigns it to the Periods field.
func (o *JobDate) SetPeriods(v []JobDatePeriodEntry) {
	o.Periods = v
}

func (o JobDate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobDate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Periods) {
		toSerialize["periods"] = o.Periods
	}
	return toSerialize, nil
}

type NullableJobDate struct {
	value *JobDate
	isSet bool
}

func (v NullableJobDate) Get() *JobDate {
	return v.value
}

func (v *NullableJobDate) Set(val *JobDate) {
	v.value = val
	v.isSet = true
}

func (v NullableJobDate) IsSet() bool {
	return v.isSet
}

func (v *NullableJobDate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobDate(val *JobDate) *NullableJobDate {
	return &NullableJobDate{value: val, isSet: true}
}

func (v NullableJobDate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobDate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


