/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the JobRequestActionSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRequestActionSummary{}

// JobRequestActionSummary struct for JobRequestActionSummary
type JobRequestActionSummary struct {
	// Role expected to fire this action.
	Actor *string `json:"actor,omitempty"`
	// Capability slugs declared on the action (e.g. client_location). Omitted when none.
	Capabilities []string `json:"capabilities,omitempty"`
	// Action key (e.g. quote, confirm_booking, complete, or a custom DYNAMIC action).
	Key *string `json:"key,omitempty"`
	// Action label, resolved to the request locale.
	Label *string `json:"label,omitempty"`
}

// NewJobRequestActionSummary instantiates a new JobRequestActionSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRequestActionSummary() *JobRequestActionSummary {
	this := JobRequestActionSummary{}
	return &this
}

// NewJobRequestActionSummaryWithDefaults instantiates a new JobRequestActionSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRequestActionSummaryWithDefaults() *JobRequestActionSummary {
	this := JobRequestActionSummary{}
	return &this
}

// GetActor returns the Actor field value if set, zero value otherwise.
func (o *JobRequestActionSummary) GetActor() string {
	if o == nil || IsNil(o.Actor) {
		var ret string
		return ret
	}
	return *o.Actor
}

// GetActorOk returns a tuple with the Actor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestActionSummary) GetActorOk() (*string, bool) {
	if o == nil || IsNil(o.Actor) {
		return nil, false
	}
	return o.Actor, true
}

// HasActor returns a boolean if a field has been set.
func (o *JobRequestActionSummary) HasActor() bool {
	if o != nil && !IsNil(o.Actor) {
		return true
	}

	return false
}

// SetActor gets a reference to the given string and assigns it to the Actor field.
func (o *JobRequestActionSummary) SetActor(v string) {
	o.Actor = &v
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise.
func (o *JobRequestActionSummary) GetCapabilities() []string {
	if o == nil || IsNil(o.Capabilities) {
		var ret []string
		return ret
	}
	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestActionSummary) GetCapabilitiesOk() ([]string, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *JobRequestActionSummary) HasCapabilities() bool {
	if o != nil && !IsNil(o.Capabilities) {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given []string and assigns it to the Capabilities field.
func (o *JobRequestActionSummary) SetCapabilities(v []string) {
	o.Capabilities = v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *JobRequestActionSummary) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestActionSummary) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *JobRequestActionSummary) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *JobRequestActionSummary) SetKey(v string) {
	o.Key = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *JobRequestActionSummary) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRequestActionSummary) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *JobRequestActionSummary) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *JobRequestActionSummary) SetLabel(v string) {
	o.Label = &v
}

func (o JobRequestActionSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRequestActionSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Actor) {
		toSerialize["actor"] = o.Actor
	}
	if !IsNil(o.Capabilities) {
		toSerialize["capabilities"] = o.Capabilities
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableJobRequestActionSummary struct {
	value *JobRequestActionSummary
	isSet bool
}

func (v NullableJobRequestActionSummary) Get() *JobRequestActionSummary {
	return v.value
}

func (v *NullableJobRequestActionSummary) Set(val *JobRequestActionSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRequestActionSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRequestActionSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRequestActionSummary(val *JobRequestActionSummary) *NullableJobRequestActionSummary {
	return &NullableJobRequestActionSummary{value: val, isSet: true}
}

func (v NullableJobRequestActionSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRequestActionSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


