/*
Crisphive Developer API

Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crisphive

import (
	"encoding/json"
)

// checks if the TechnicianServiceAreasResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TechnicianServiceAreasResponse{}

// TechnicianServiceAreasResponse struct for TechnicianServiceAreasResponse
type TechnicianServiceAreasResponse struct {
	// The service areas now assigned to the technician.
	ServiceAreas []TechnicianServiceAreaRef `json:"service_areas,omitempty"`
}

// NewTechnicianServiceAreasResponse instantiates a new TechnicianServiceAreasResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTechnicianServiceAreasResponse() *TechnicianServiceAreasResponse {
	this := TechnicianServiceAreasResponse{}
	return &this
}

// NewTechnicianServiceAreasResponseWithDefaults instantiates a new TechnicianServiceAreasResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTechnicianServiceAreasResponseWithDefaults() *TechnicianServiceAreasResponse {
	this := TechnicianServiceAreasResponse{}
	return &this
}

// GetServiceAreas returns the ServiceAreas field value if set, zero value otherwise.
func (o *TechnicianServiceAreasResponse) GetServiceAreas() []TechnicianServiceAreaRef {
	if o == nil || IsNil(o.ServiceAreas) {
		var ret []TechnicianServiceAreaRef
		return ret
	}
	return o.ServiceAreas
}

// GetServiceAreasOk returns a tuple with the ServiceAreas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TechnicianServiceAreasResponse) GetServiceAreasOk() ([]TechnicianServiceAreaRef, bool) {
	if o == nil || IsNil(o.ServiceAreas) {
		return nil, false
	}
	return o.ServiceAreas, true
}

// HasServiceAreas returns a boolean if a field has been set.
func (o *TechnicianServiceAreasResponse) HasServiceAreas() bool {
	if o != nil && !IsNil(o.ServiceAreas) {
		return true
	}

	return false
}

// SetServiceAreas gets a reference to the given []TechnicianServiceAreaRef and assigns it to the ServiceAreas field.
func (o *TechnicianServiceAreasResponse) SetServiceAreas(v []TechnicianServiceAreaRef) {
	o.ServiceAreas = v
}

func (o TechnicianServiceAreasResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TechnicianServiceAreasResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceAreas) {
		toSerialize["service_areas"] = o.ServiceAreas
	}
	return toSerialize, nil
}

type NullableTechnicianServiceAreasResponse struct {
	value *TechnicianServiceAreasResponse
	isSet bool
}

func (v NullableTechnicianServiceAreasResponse) Get() *TechnicianServiceAreasResponse {
	return v.value
}

func (v *NullableTechnicianServiceAreasResponse) Set(val *TechnicianServiceAreasResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTechnicianServiceAreasResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTechnicianServiceAreasResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTechnicianServiceAreasResponse(val *TechnicianServiceAreasResponse) *NullableTechnicianServiceAreasResponse {
	return &NullableTechnicianServiceAreasResponse{value: val, isSet: true}
}

func (v NullableTechnicianServiceAreasResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTechnicianServiceAreasResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


